import {canReceiveSkillReward,createPlayerBuild} from '../../src/next/core/playerBuild.ts';
import {trophyDefinitions} from '../../src/next/meta/trophies.ts';
import {frozenRuleDescription} from '../../src/next/core/boxTypes.ts';
import { encounterBandsV2 } from '../../src/next/app/encounters.ts';
import { enemyRoster,getEnemyDefinition } from '../../src/next/core/monsters.ts';
import { monsterNotes } from '../../src/next/ui/monsterPresentation.ts';
import {readFileSync,writeFileSync} from 'node:fs';
import {META,treeNodes,levelInfo,availableBoards} from '../../src/next/meta/profile.ts';
import {roster,rosterIds} from '../../src/next/meta/roster.ts';
import {KIT_ROLES} from '../../src/next/meta/kits.ts';
import {boardSkillName,currentBoardInformation,currentFormInformation} from '../../src/next/ui/kitInformation.ts';
import {normalSkillIds,skillCatalog,skillName,skillDescription,skillValue} from '../../src/next/core/skillCatalog.ts';
import {PRESENTATION_VERSION} from '../../src/next/version.ts';
import {trialTuning} from '../../src/next/config.ts';
import {boxTypeIds,boxTypeLabels} from '../../src/next/core/boxTypes.ts';
const escape=(s:string|number)=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const empty={three:0,four:0,five:0,slots:0,board:0};
export function playerGuideData(){const levels=Array.from({length:META.maxLevel},(_,i)=>{let xp=0;while(levelInfo(xp).level<i+1)xp++;return {level:i+1,xp,points:levelInfo(xp).points};});return {version:PRESENTATION_VERSION,encounters:encounterBandsV2,monsters:enemyRoster.map(id=>({...getEnemyDefinition(id),note:monsterNotes[id]})),levels,economy:META,tree:treeNodes,characters:rosterIds.map(id=>{const r=roster[id],free=availableBoards(empty,id),unlocked=availableBoards({...empty,board:1},id).filter(b=>!free.includes(b));return {...r,role:KIT_ROLES[id],fixedName:skillName(r.starter,1),form:currentFormInformation(id),boards:[...free.map(b=>({id:b,name:boardSkillName(b),access:b===r.board?'初期装備':'最初から選べる互換スキル',description:currentBoardInformation(b)})),...unlocked.map(b=>({id:b,name:boardSkillName(b),access:'ツリー3ptで解放',description:currentBoardInformation(b)}))]};}),skills:normalSkillIds.map(id=>({id,name:skillName(id,1),access:skillCatalog[id].rewardAccess??'shared',base:skillDescription(id,1,trialTuning),plus:id==='poison-craft'||skillCatalog[id].upgradeable===false?null:skillDescription(id,2,trialTuning)})),types:boxTypeIds.map(id=>({id,name:boxTypeLabels[id]}))};}
export function playerGuideHtml(){const d=playerGuideData(),e=escape;const board=(b:ReturnType<typeof playerGuideData>['characters'][number]['boards'][number])=>`<li><strong>${e(b.name)}</strong><span class="tag">${e(b.access)}</span><p>${e(b.description)}</p></li>`;
const characters=d.characters.map(c=>`<details id="character-${c.id}" class="character"><summary><span>${e(c.name)}</span><small>${e(c.role)}${c.prototype?' · 試作キット':''}</small></summary><div class="inside"><p class="stats">初期HP <b>${c.hp}</b>　3 / 4 / 5以上リンクの基礎火力 <b>${c.attacks[3]} / ${c.attacks[4]} / ${c.attacks[5]}</b></p><p>固定スキル：<strong>${e(c.fixedName)}</strong>。自由枠は出発時には空きです。</p><h4>盤面スキル</h4><ul class="boards">${c.boards.map(board).join('')}</ul><h4>変化</h4><p>${e(c.form)}</p>${c.id==='violet'?'<p>毒盛り術は、現在の自箱2×2を左上の位置ごとに数えます。重なる形も別に数え、2×3なら2形、3×3なら4形。自分が付与した毒箱1個ごとにこの数を加算し、所有者の全手番終了時に再計算します。毒の付与者と箱の所有者は別なので、捕獲した自分の毒箱が自分を傷つけることもあります。</p>':''}</div></details>`).join('');
const skills=d.skills.map(s=>`<article id="${s.id}" class="skill"><h3>${e(s.name)}</h3><span class="tag">${s.access==='never'?'バイオレット固定・＋強化なし':s.access==='starter-upgrade-only'?'青の固定・＋強化のみ':s.access==='trophy'?'トロフィー限定・ガチャ対象外':'共有スキル'}</span><p>通常：${e(s.base)}${s.plus?`<br>＋：${e(s.plus)}`:''}</p></article>`).join('');
return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game1 プレイガイド · 育成と8人の仲間</title><style>
:root{font-family:system-ui,"Noto Sans JP",sans-serif;color:#392e45;background:#eef4f0;line-height:1.8}*{box-sizing:border-box}body{max-width:980px;margin:auto;padding:24px 20px 60px}a{color:#85375e;text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #963a6e;outline-offset:4px}header{padding:28px 0 24px;border-bottom:2px solid #8a4770}header small{letter-spacing:.14em;color:#70566e}h1{font-size:clamp(26px,5vw,42px);line-height:1.35;margin:12px 0}h2{font-size:24px;line-height:1.4;margin:0 0 18px}h3{font-size:18px;margin:0}h4{font-size:16px;margin:20px 0 6px}p{margin:10px 0}nav{display:flex;flex-wrap:wrap;gap:8px 18px;margin:16px 0}nav a,.top-link{display:inline-flex;align-items:center;min-height:44px}section{padding:28px 0;border-bottom:1px solid #cbd5cf;scroll-margin-top:16px}.notice{border-left:4px solid #9b527a;background:#fff;padding:16px 20px}.tag{display:inline-block;color:#75516c;font-size:12px;margin:3px 0 3px 10px}.stats{font-variant-numeric:tabular-nums}.numbers{display:grid;grid-template-columns:repeat(auto-fit,minmax(104px,1fr));gap:8px;margin:18px 0}.numbers div{background:white;border:1px solid #d8dfda;padding:9px 12px;border-radius:6px}.numbers b,.numbers small{display:block}.numbers small{color:#6c6170}li{margin:7px 0}ul,ol{padding-left:24px}.character{background:#fff;border:1px solid #d1dad3;border-radius:8px;margin:12px 0;scroll-margin-top:12px}.character summary{cursor:pointer;min-height:58px;padding:13px 18px;font-weight:750}.character summary span{font-size:19px}.character summary small{font-weight:450;margin-left:14px;color:#67596c}.inside{padding:0 20px 22px}.boards{padding:0;list-style:none}.boards li{padding:12px 0;border-bottom:1px solid #e3e8e4}.boards p{font-size:14px}.skill-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.skill{background:#fff;padding:18px;border:1px solid #d5ded7;border-radius:8px}.skill .tag{margin-left:0}.skill p{font-size:14px}.type-list dt{font-weight:750;margin-top:18px}.type-list dd{margin-left:0}.muted,footer{color:#6b5d70;font-size:14px}footer{padding-top:24px}@media(max-width:560px){body{padding:16px 16px 40px}section{padding:24px 0}.inside{padding:0 14px 18px}.character summary small{display:block;margin-left:16px}.skill-grid{grid-template-columns:1fr}}
</style></head><body><a class="top-link" href="/next/">← Game1を開く</a>　<a href="/docs/">資料一覧</a><header><small>GAME 1 / PLAYER GUIDE · v${e(d.version)}</small><h1>育てて、組んで、<br>もう一度50階へ。</h1><p>キャラを選び、経験値ツリーと盤面スキル、選択スキルを準備して出発します。コインはプレイで獲得するものだけ。課金・有料通貨はありません。</p><p class="notice">このガイドは<strong>新しく出発するラン</strong>の現在の数値です。ホームの「盤面スキル」は次の出発、戦闘中の「詳細」は保存済みランの能力を表示します。以前のランの構成や育成条件を途中で置き換えません。</p></header>
<nav aria-label="ガイドの目次"><a href="#start">出発と帰還</a><a href="#growth">育成</a><a href="#gacha">ガチャ</a><a href="#roster">8人の仲間</a><a href="#pool">選択スキル</a><a href="#skills">スキル一覧</a><a href="#monsters">敵と出現階層</a><a href="#types">箱タイプとボス</a><a href="#save">保存と記録</a><a href="#verification">確認したこと</a></nav>
<section id="start"><h2>出発と、報酬を受け取るタイミング</h2><ol><li>所持キャラのカードを1回タップして切り替え</li><li>「経験値ツリー」「盤面スキル」「選択スキル」で次のランを準備</li><li>「ラン開始」で構成を固定して出発。進行中のランは「続きから」で再開</li></ol><p>正式ランの終了時に、記録された撃破1体につき<strong>${META.coinsPerEnemy}コイン・そのキャラの${META.xpPerEnemy}EXP</strong>を一度受け取ります。敗北でも撃破分は残ります。50階を生存してクリアすると毎回${META.clearCoins}コイン・${META.clearXp}EXPを追加し、合計<strong>450コイン・750EXP</strong>です。</p><h3>続ける / 帰還する</h3><p>ホームを開いただけではランは終わりません。「帰還する」は、キャラ・撃破数・報酬を確認して終了する別の操作です。正式ランなら撃破分を受け取れます。0体なら0。途中の敵へのダメージは数えず、クリア追加報酬・クリアトロフィーは付きません（新規ラン中に達成したダメージ・最大HP実績は保持）。</p><p>帰還できるのは、自動処理が終わった自分の行動選択中だけです。報酬を確定・スキップした後も、赤の追加投入などの解決は省略しません。キャンセルすれば続けられます。帰還後はそのランを再開できず、新しいランも自動では始まりません。</p><p class="muted">検証ランや正式出発の記録がないランは精算対象外です。記録のない過去のプレイへ遡って報酬・トロフィーを付けることはありません。</p></section>
<section id="interaction"><h2>今回の操作変更</h2><p>戦闘画面の上に「速度 通常／短縮」を常設しました。次の行動から反映し、設定はこのブラウザに保存します。端末またはゲームの動き低減が有効な場合は「低減で短縮」と表示し、安全のため低減設定は維持します。音はベルのSE＝効果音、音符のBGM＝音楽。斜線とOFF表示で停止状態を示し、別々に切り替えます。歯車で音量と演出を調整できます。戦闘ログは設定内の専用ボタンで開きます。速度ごとに投入・着弾・HP表示・技の終わりを同期し、技の表示が終わる前に次の手番へ進まないようにしました。</p><p>ホームの出発ボタン上でBGMのON/OFFと音量を調整できます。設定はステージと共通で、出発・帰還・ボス戦で曲だけ切り替わります。BGM設定はこのブラウザに保存されます。保存したONも、ページを開き直した後は「再開」をタップするまで鳴りません。効果音は別設定です。</p><ul><li>ラン開始でHP・火力・持ち込み構成を確認してから出発します</li><li>所持スキルは盤面下の小さなカードに常設。形やリンク数のアイコンをタップするとカードを開き、即時発動スキルはそこから使用できます</li><li>ガチャはハンドルからカプセルが出る演出へ。閉じても抽選と残高は保存され、結果は変わりません</li><li>投入点は各盤面の実際の辺に表示。内部天井も扱い、大きな盤面は盤面領域だけスクロールできます</li></ul></section><section id="growth"><h2>キャラごとの経験値ツリー</h2><p>Lv1で${META.initialPoints}pt、以後1レベルごとに${META.pointsPerLevel}pt。新育成の上限は<strong>Lv${META.maxLevel}・24pt</strong>で、火力3種と報酬回復は初期上限5段階＋レベル÷5の切り捨てです（Lv5で6、Lv10で7）。自由枠は最大4枠、盤面解放は1段階のままです。報酬回復は1段階ごとにBUILD REWARDの即時回復＋2、基本10から最大HPまで。ヘルス・ポーションなど他の回復は増えません。出発前は無料で振り直せます。ランで得たEXPは終了時に精算し、育成や設定変更は進行中のランを途中で強化しません。</p><ul>${Object.values(treeNodes).map(n=>`<li><strong>${e(n.name)}</strong>：${e(n.description)}。初期上限${n.max}段階、1段階${n.cost}pt</li>`).join('')}</ul><h3>必要な累計EXP</h3><div class="numbers">${d.levels.map(v=>`<div><b>Lv${v.level}</b><small>${v.xp.toLocaleString('ja-JP')} EXP / ${v.points}pt</small></div>`).join('')}</div><h3>経験値エナジー</h3><p>ホーム右上の✧から使用できます。1個＝${META.energyXp}EXP。成長途中の所持キャラに使うと、その場でキャラのEXPに加算します。上限をまたぐ分も全量保存しますが、上限到達後のキャラには使えません。たとえば750EXPから3個使うと900EXP、Lv9になります。全キャラが上限なら、現時点ではエナジーの使用先はありません。</p><p>以前の高いレベル・獲得ポイント・EXPは保持します。現在のツリーで使えない旧ポイントは記録として残り、画面には割り振れる残りポイントだけを表示します。今の上限を超える強化や将来の使用を保証するものではありません。</p></section>
<section id="gacha"><h2>コインガチャ</h2><p>1回<strong>${META.gachaCost}コイン</strong>。カテゴリの確率は毎回一定です。</p><ul><li><strong>キャラクター${META.characterRate}%</strong>：青・赤以外の6人。未所持がいる間はその中から均等に抽選します。残りN人なら1人あたり全体の20÷N%。最初は各約3.33%、最後の1人は20%</li><li>6人とも所持した後は全6人から均等。キャラ重複はエナジー${META.duplicateCharacterEnergy}個に交換</li><li><strong>共有スキル${META.skillRate}%</strong>：24種類から均等、各約1.67%。うち6種は最初から所持。重複は${META.duplicateSkillCoins}コインに交換</li><li><strong>経験値エナジー2個：${META.energyRate}%</strong></li></ul><p>天井や「何回で必ず加入」という保証はありません。未所持優先でもキャラ以外が続くことはあります。保存済みの結果は再読込で変わらず、前回の結果を確認してから次を引きます。</p></section>
<section id="roster"><h2>8人の仲間と盤面スキル</h2><p>青の子・ルビィは最初から所持。ほかの6人はガチャで加入します。下の名前を開くと、初期能力・すべての盤面選択肢・変化を確認できます。<strong>盤面スキルは1種類だけ持ち込み、どれも通常行動1手を使います。</strong>ゲージやHPは追加コストです。</p><p class="muted">ミント・アンバー・バイオレット・シルバー・ローズは試作キットです。新しい出発は各キャラ固有の盤面スキルから選びます。ツリーで各キャラ2種の新技能を解放できます。保存済みランの旧構成は維持します。</p>${characters}</section>
<section id="pool"><h2>所持品・選択スキル・装備枠は別</h2><ul><li>選択スキルはラン中のスキル報酬に出す候補。使用可能な<strong>${META.poolMin}〜${META.poolMax}種類</strong>を選び、出発時に固定します。トロフィーを含む全所持時の候補は青35、ほか34種類です（選択できるのは最大20種類）</li><li>ガチャで得たスキルは所持品に追加されます。使いたいキャラのプールに手動で加え、ラン中の報酬で選びます。自由枠に最初から装備されるわけではありません</li><li>スキル報酬は最大3択。＋を所持中のスキルは外れるので候補が減る場合があります。強化が済んだ構成では入れ替え候補だけになることもあります</li><li>ヘルスは青の固定スキル専用。ほかのキャラの候補・自由枠には入りません。毒盛り術はバイオレット固定で、通常報酬・ガチャ・＋強化の対象外です</li></ul><p>少ない候補は狙いを絞りやすく、多い候補は組み替えの幅が広がります。カードは1回タップでON/OFFを切り替えます。固有スキルは固定です。</p></section>
<section id="skills"><h2>通常スキル35種と専用パッシブ（計36種）</h2><p>以下は基礎値です。形スキルは能動投入の起点を含む形で発動し、同じ技能は1投入につき1回。ヘルスの戦闘内回数上限はありません。変化・輝き・フローズンなどは別途適用します。</p><div class="skill-grid">${skills}</div></section>
<section id="monsters"><h2>敵の種類と出現階層</h2><p>v1.10の新しい50階ランでは、階層ごとに異なる候補から敵を抽選します。同じシード・同じ階数なら同じ敵です。抽選は戦闘中の乱数や報酬の抽選に影響しません。<strong>以前の保存ランは最後まで旧出現順を維持します。</strong></p><ul>${d.encounters.bands.map(b=>`<li><strong>${b.from}–${b.to}階</strong>：${b.pool.map(x=>`${e(getEnemyDefinition(x.enemyId).label)}（重み${x.weight}）`).join('、')}</li>`).join('')}</ul><p>1–24階は通常投入と基本リンク攻撃だけ。26–39階で回復・氷結・トゲを1種類ずつ学び、41–49階では上位の氷結・トゲに加え、正確な4連で毒を付けるデビルモンと、高火力の通常投入型シャシャークが出現します。複数のギミックを一体へ重ねていません。25・40・50階は抽選より優先される固定ボスです。</p><div class="skill-grid">${d.monsters.map(m=>`<article class="skill"><h3>${e(m.label)}</h3><p>基礎HP ${m.maxHp} · 3/4/5連以上 ${m.attacks[3]}/${m.attacks[4]}/${m.attacks[5]}</p><p>${e(m.note)}</p></article>`).join('')}</div><p>デビルモンは4連の軸ごとにタイプなしの自箱1個をランダムでどくにし、複数軸なら別々の箱を選びます。5連以上・受動変換では発動しません。既存タイプは上書きせず、対象なしなら乱数も使いません。毒の付与者は敵で、毒ダメージは次の自手番終了からです。両新種の基礎HP48 / 52は同帯の既存種に合わせた暫定値です。上のHPは基礎値です。1周目の実HPは基礎HP＋（階数−1）×10。画面内の「敵の基本火力」は実際の補正後の値です。氷結は未凍結の自箱を上から、同じ行なら左から選択します。対象なしなら投入せず終了。次の行動は画面上部、周期と対象位置は詳細で確認できます。トゲ投入は既存のトゲ処理を使い、敵自身も隣接トゲのダメージを受けます。</p><details><summary>定義書とモンスターデータの分け方 / Definitions vs monster data</summary><p>共通定義書は「リンク、能動投入、手番終了、1箱1タイプ、フローズン、トゲ、KO後の停止」の意味を定義します。モンスターデータはその定義を参照し、ID・名前・HP・攻撃表・行動周期を記述します。出現階は別の出現表で範囲と重みを管理し、ボスだけ固定上書きします。</p><p>Common definitions own the meaning of links, insertion, turn-end effects, single box types and KO boundaries. Monster data supplies identity, stats and behavior parameters. Separate encounter bands own stage ranges and weights; fixed bosses override random pools.</p><p>各モンスターへ1–24など全階の配列を埋め込む方式は採用しません。新しい敵は再利用できる定義を追加し、必要な帯の候補へIDを参照させます。例外は固定ボス表へ追加。出現表の変更時は新しい版を作り、保存ランの版を変更しません。</p><p>Do not repeat every floor inside each monster. Add a reusable monster, reference its ID in a weighted band, and use explicit overrides for fixed encounters. Publish a new encounter version for changes; saved runs keep their original version.</p></details></section>
<section id="types"><h2>1箱に1タイプ。付与は上書き</h2><p>所有者とタイプは別です。敵箱を自箱へ捕獲してもタイプは残ります。タイプの上書きや受動落下だけで、新しいリンク・形は発動しません。</p><dl class="type-list"><dt>輝き</dt><dd>そのリンク・形に1個以上含まれると、そのリンクのダメージとゲージ獲得、またはその形のダメージと回復量が2倍。複数でも重複しません</dd><dt>フローズン</dt><dd>${e(frozenRuleDescription({frozenRule:'half-melt-v1'} as import('../../src/next/core/types.ts').BattleConfig))} 既存の保存ランは従来の1個につき−1を維持します</dd><dt>絶対零度</dt><dd>リンク攻撃力を半減し、攻撃後も溶けません。フローズンと合わせても半減は1回です</dd><dt>どく / げきどく（もうどく）</dt><dd>所有者の全手番終了時、所有箱1個につき基礎1 / 2ダメージ。毒盛り術は自分が付与した箱にだけ現在の自箱2×2の数を加算します</dd><dt>ガレキ</dt><dd>重力と反対方向の直上に2箱以上積まれると崩れます。再落下は受動で、リンク・形を発動しません</dd><dt>トゲ</dt><dd>既存トゲの周囲8マスへ能動投入した直後、投入者に最大HPの2%ダメージ。トゲ1個ごと切り捨て・最低1が現在の丸めです。形・リンクより先に処理し、受動落下や変換では発動しません</dd></dl><h3>50階までのボス</h3><p>25・40階にスピードコア、50階にマザーコア。スピードコアは自身5手番ごとに固定3ダメージの後で投入します。マザーコアは投入4手→待機1手→2回投入2手。HP20%以下に入ると次の敵手番から固定5＋投入→投入の2手周期です。2回投入は順に解決し、途中でKOなら残りは中止します。</p><p>音は初めOFF。効果音とBGMは別々に開始・停止できます。ホーム専用Starlight Terminal・通常曲・中ボス曲・マザーコア曲が画面に合わせて切り替わります。新しい6キャラの変化音は現在、既存の赤の変化音を共用しています。</p></section>
<section id="save"><h2>トロフィーと保存</h2><p>初50階・8人別クリア・自手番100ダメージ・最大HP100の計<strong>11個</strong>。キャラ別クリア8種と全体実績2種で、スキル10種を一度だけ所持に追加します。記録済みのクリア実績には遡って付与します。新しい2実績はv1.12からの正式出発で観測し、未記録の過去実績や検証ランからは付与しません。</p><ul>${trophyDefinitions.filter(t=>t.skill).map(t=>`<li>${e(t.condition)} → <strong>${e(skillName(t.skill!,1))}</strong></li>`).join('')}</ul><p>実ダメージは1回の自手番の追加投入・複数軸・形・直接攻撃を合算し、過剰ダメージと敵手番中の毒を除外します。解放は自動装備ではなく、次の出発用プールへ手動で追加します。進行中の候補は変わりません。大振り攻撃は5以上リンクへ現在の5リンク火力の50%（＋100%）を追加し、端数切り捨て。救急箱は上段が自箱・任意・自箱、下段が自箱3個。回転不可、任意マスは空・敵箱も可、基礎10回復・＋なし。輝き・青の既存回復連動は通常通りです。</p><p class="notice">戦闘セーブと成長データは<strong>この端末・ブラウザ内</strong>に保存されます。アカウント同期・クラウド保存はありません。ブラウザのデータ削除や端末変更に備え、ホームの記録・保存メニューから成長データをファイルへ保存してください。</p><p>成長バックアップに戦闘途中のセーブは含まれません。復元は進行中のランを終えてから行い、復元前の成長データも端末内に1世代残します。保存エラー時は表示される再試行・保存済み状態への復帰を使ってください。新しい形式のセーブは古い版では再開できない場合があります。</p></section>

<section id="verification"><h2>確認したことと、残っている課題</h2><h3>v1.12の限定比較</h3><p>新スキルは現在の盤面条件、救急箱の固定形・回転禁止・基礎10回復、過剰ダメージを除く実績、保存失敗後の重複なし復帰を確認しています。バイオレットの新しい基礎火力1/2/3は毒の比重を高めます。成長なし・1階だけ・同じ32シードの自動操作比較では、旧火力4/7/12で30体、新火力で18体を撃破。四角の準備を重視する別方針では31体と20体、新火力＋毒際攻めは23体でした。これは<strong>人の勝率や50階クリア率ではありません</strong>。毒が実ダメージの約58〜61%を占め、盤面準備を要する傾向を確認した限定試験です。</p><p>救急箱は敵の抵抗を除いた24回の合法投入で7回・計70回復しましたが、3列が満杯になりました。繰り返し発動は仕様であり、この条件で無限回復は確認していません。輝きと青の回復連動は既存仕様を維持します。</p><p>今回の追加スキル・盤面技能は発動条件と保存互換を検査していますが、新技能を含む長期のバランス評価はまだありません。以下の自動比較は追加前のキットに対する過去の検証です。</p><p>戦闘処理・保存の復旧・報酬の重複防止などを自動テストで確認しています。バランスは別に、旧出現表で、育成Lv8の同条件で全8キャラ・計288ランを自動操作して比較しました。新しい階層別の敵に対するクリア率を示す検証ではありません。報酬や行動の選び方で結果が変わるため、<strong>この結果は人のクリア率や、全キャラの強さが等しいことを示すものではありません。</strong></p><p>ローズとバイオレットは、とくに終盤の安定性に確認すべき課題が残る試作キットです。ローズの変化は現在も<strong>横リンク＋12</strong>です。＋18案を別枠で32ランずつ2回比較しましたが、安定した改善を十分に確かめられず、採用していません。</p><p class="muted">最新画面を再読込した後の操作、iOS実機での動作、音の実聴品質は今回確認できていません。自動テストの合格だけで、すべての端末や操作の問題がないとは言い切れません。</p></section>
<footer><p>開発中の試作です。数値は今後調整される場合があります。従来スキルの基礎値を維持し、新しい通常スキル15種を追加しました。このガイドはv${e(d.version)}の新出発に対応しています。旧1.0・スキル実験・以前の定義書は比較用です。</p><nav><a href="/next/">Game1へ戻る</a><a href="/docs/">以前の資料</a><a href="game1_content_catalog_next.json" download>定義データを保存</a></nav></footer></body></html>`;}
if(process.argv[1]?.endsWith('build-player-guide.mts')){const jsonPath=new URL('../../public/docs/game1_content_catalog_next.json',import.meta.url);const old=JSON.parse(readFileSync(jsonPath,'utf8'));old.playerGuide=playerGuideData();old.revision='1.12';old.skills=normalSkillIds.filter(id=>id!=='poison-craft').map(id=>({id,name:skillName(id,1),kind:skillCatalog[id].kind,initialRewardEligible:{blue:canReceiveSkillReward(createPlayerBuild('blue'),id),red:canReceiveSkillReward(createPlayerBuild('red'),id)},requiresTrophy:skillCatalog[id].rewardAccess==='trophy',rewardAccess:skillCatalog[id].rewardAccess??'shared',baseValues:[skillValue(id,1,trialTuning),skillValue(id,2,trialTuning)],effects:[skillDescription(id,1,trialTuning),...(skillCatalog[id].upgradeable===false?[]:[skillDescription(id,2,trialTuning)])]}));old.trophies=trophyDefinitions;old.title='Game1 プレイガイド・育成と8人の仲間';old.presentationSupplement.revision=PRESENTATION_VERSION;writeFileSync(jsonPath,JSON.stringify(old,null,2)+'\n');writeFileSync(new URL('../../public/docs/game1_content_catalog_next.html',import.meta.url),playerGuideHtml());}
