import test from 'node:test';import assert from 'node:assert/strict';
import {createProfile,freezeRunMeta} from '../src/next/meta/profile.ts';import {prepareDeparture} from '../src/next/meta/departure.ts';import {rosterIds} from '../src/next/meta/roster.ts';
import {LEGACY_KIT_BALANCE,CURRENT_KIT_BALANCE,amberPowerCandidate,kitBalanceOf,validateKitBalance} from '../src/next/meta/kitBalance.ts';
import {createBattle,applyAction,getDropOptions,getAvailableBoardSkills,canManualTransform,needsTurnStart} from '../src/next/core/index.ts';
import {kitBoardTargets,kitBoardDefinition} from '../src/next/core/kitBoards.ts';import {carryTransformationState} from '../src/next/core/transformations.ts';
import {BattleController} from '../src/next/app/BattleController.ts';import {encodeSave,decodeSave,validateCheckpoint,SAVE_RULES,SNAPSHOT_SAVE_RULES} from '../src/next/app/saveCheckpoint.ts';import {createNextStageConfig} from '../src/next/app/BattleRun.ts';
import type {BattleAction,BattleConfig,BattleState,Box} from '../src/next/core/types.ts';import type {RosterId} from '../src/next/meta/roster.ts';
const b=(row:number,col:number,owner:Box['owner']='player',type:Box['type']='normal'):Box=>({id:`${row}:${col}`,row,col,owner,type,status:'normal'});
const view={render(){},async animate(){}};
const plain=(x:unknown)=>JSON.parse(JSON.stringify(x, (key,value)=>key==='kitBalance'?undefined:value));
function setup(id:RosterId){const p=createProfile(1);p.ownedCharacters=[...rosterIds];return prepareDeparture(freezeRunMeta(p,id,false),23);}
function choice(s:BattleState,n:number):BattleAction{if(needsTurnStart(s))return {type:'start-turn'};if(canManualTransform(s))return {type:'transform'};if(s.actor==='enemy')return {type:'enemy'};const skill=getAvailableBoardSkills(s)[0];if(skill&&(n%3===0||!getDropOptions(s).some(x=>x.available))){if(skill==='pain-shared')return {type:'board-skill',skillId:skill,row:7};if(skill==='ember'||skill==='imashiru-insight')return {type:'board-skill',skillId:skill};for(let row=0;row<8;row++)for(let col=0;col<6;col++)for(let orientation=0;orientation<4;orientation++)if(kitBoardTargets(s,skill,{row,col,orientation}).length)return {type:'board-skill',skillId:skill,target:{row,col,orientation}};}const drops=getDropOptions(s).filter(x=>x.available);return drops.length?{type:'drop',candidateId:drops[n%drops.length]!.id}:{type:'skip'};}
test('new departures use only the adopted one-turn power change; metadata owns a detached snapshot',()=>{assert.deepEqual(CURRENT_KIT_BALANCE,amberPowerCandidate(1));const {amber:_a,...currentOther}=CURRENT_KIT_BALANCE,{amber:_b,...legacyOther}=LEGACY_KIT_BALANCE;assert.deepEqual(currentOther,legacyOther);const x=setup('amber'),snapshot=x.config.meta!.kitBalance!;assert.notEqual(snapshot,CURRENT_KIT_BALANCE);assert.deepEqual(snapshot,CURRENT_KIT_BALANCE);const state=createBattle(x.config);assert(Object.isFrozen(state.config.meta!.kitBalance));assert.equal(kitBalanceOf({...x.config,meta:{...x.config.meta!,progressionVersion:undefined,kitBalance:undefined}}),LEGACY_KIT_BALANCE);});
test('explicit legacy snapshots and absent snapshots produce identical8-character effects and continuation',()=>{for(const id of rosterIds){const x=setup(id),config:BattleConfig={...x.config,meta:{...x.config.meta!,kitBalance:LEGACY_KIT_BALANCE},initialGauge:id==='imashiru'?230:120,combatants:{player:{...x.config.combatants.player,maxHp:1000,initialHp:1000},enemy:{...x.config.combatants.enemy,maxHp:1000,initialHp:1000}},initialBoxes:[b(7,0),b(7,1),b(6,0),b(7,3,'enemy'),b(7,4,'enemy')]};let current=createBattle(config),old=createBattle({...config,meta:{...config.meta!,kitBalance:undefined}});for(let n=0;n<45&&!current.result;n++){const action=choice(current,n),a=applyAction(current,action),z=applyAction(old,action);assert.deepEqual(plain(a),plain(z),`${id} action${n}`);assert(a.accepted,`${id} rejected ${JSON.stringify(action)}`);current=a.state;old=z.state;}}});
test('old checkpoints retain absent snapshots byte-for-byte through Continue and never acquire candidate rules',async()=>{const x=setup('amber'),config={...x.config,meta:{...x.config.meta!,progressionVersion:undefined,kitBalance:undefined}},c=new BattleController(config,view,x.options);await c.start();await c.drop('ceiling:0:0');const cp=decodeSave(encodeSave(c.exportCheckpoint(),1,1)).checkpoint,raw=JSON.stringify(cp);const restored=BattleController.restore(cp,view);await restored.start();assert.equal(JSON.stringify(restored.exportCheckpoint()),raw);assert.equal(restored.snapshot.config.meta!.kitBalance,undefined);assert.equal(kitBalanceOf(restored.snapshot.config).amber.mode,'link-gauge');});
test('candidate board costs come from the saved snapshot, not the current catalog',()=>{const x=setup('amber'),balance=structuredClone(LEGACY_KIT_BALANCE);(balance.boards['amber-convert'] as {gauge:number}).gauge=7;const s=createBattle({...x.config,meta:{...x.config.meta!,kitBalance:balance},initialGauge:7,initialBoxes:[b(7,0,'enemy')]});assert.equal(kitBoardDefinition(s.config,'amber-convert')!.gauge,7);const r=applyAction(s,{type:'board-skill',skillId:'amber-convert',target:{row:7,col:0}});assert(r.accepted);assert.equal(r.resolution!.events.find(e=>e.type==='gauge-spent')!.amount,7);assert.equal(LEGACY_KIT_BALANCE.boards['amber-convert'].gauge,20);});
test('Amber power candidate multiplies eligible links before shiny/frozen, never shape damage or gauge',()=>{const x=setup('amber'),config={...x.config,frozenRule:undefined,meta:{...x.config.meta!,kitBalance:amberPowerCandidate(1)},initialGauge:100,initialBoxes:[b(7,0,'player','shiny'),b(7,1,'player','frozen')]};const t=applyAction(createBattle(config),{type:'transform'}).state,r=applyAction(t,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.resolution!.events.find(e=>e.type==='attack')!.damage,23);assert.equal(r.resolution!.events.filter(e=>e.type==='gauge').find(e=>e.source==='link')!.amount,4);assert.equal(r.state.transformation,null);
 const shape=createBattle({...config,initialBoxes:[b(7,0),b(6,0),b(7,1)]}),shaped=applyAction(applyAction(shape,{type:'transform'}).state,{type:'drop',candidateId:'ceiling:1:0'});assert.equal(shaped.resolution!.events.filter(e=>e.type==='damage').find(e=>e.source==='square-strike')!.damage,5);
});
test('two-own-turn power form resumes exactly once, expires on second ordinary action and clears at stage end',async()=>{const x=setup('amber'),config={...x.config,meta:{...x.config.meta!,kitBalance:amberPowerCandidate(2)},initialGauge:100,combatants:{...x.config.combatants,enemy:{...x.config.combatants.enemy,maxHp:999,initialHp:999}},initialBoxes:[b(7,0),b(7,1)]};const c=new BattleController(config,view,x.options);await c.start();await c.transform();assert.equal(c.snapshot.turn,1);await c.drop('ceiling:2:0');assert.equal(c.snapshot.transformation?.character,'amber');assert.equal((c.snapshot.transformation as {remainingOwnTurns:number}).remainingOwnTurns,1);const cp=decodeSave(encodeSave(c.exportCheckpoint(),1)).checkpoint;validateCheckpoint(cp);const restored=BattleController.restore(cp,view);await restored.start();assert.deepEqual(JSON.parse(JSON.stringify(restored.snapshot)),JSON.parse(JSON.stringify(c.snapshot)));await c.drop('ceiling:3:0');await restored.drop('ceiling:3:0');assert.deepEqual(JSON.parse(JSON.stringify(restored.snapshot)),JSON.parse(JSON.stringify(c.snapshot)));assert.equal(c.snapshot.transformation,null);
 const won={...cp.state,hp:{...cp.state.hp,enemy:{...cp.state.hp.enemy,current:0}},result:{winner:'player',reason:'hp-zero'}} as BattleState;const next=carryTransformationState(createBattle(createNextStageConfig(config,won,'hikikizan',2)),won);assert.equal(next.transformation,null);assert.deepEqual(next.config.meta!.kitBalance,config.meta.kitBalance);
});
test('unknown or malformed balance snapshots and invalid form timers fail closed without changing inputs',()=>{const x=setup('amber');for(const mutate of [(b:any)=>b.version=2,(b:any)=>b.boards=[],(b:any)=>delete b.boards['amber-convert'],(b:any)=>b.amber.mode='unknown',(b:any)=>b.amber.ownTurns=0,(b:any)=>b.boards['blue-freeze'].gauge=-1,(b:any)=>b.silverBarrier=Infinity]){const balance=structuredClone(LEGACY_KIT_BALANCE);mutate(balance);const raw=JSON.stringify(balance);assert.throws(()=>validateKitBalance(balance));assert.throws(()=>createBattle({...x.config,meta:{...x.config.meta!,kitBalance:balance}}));assert.equal(JSON.stringify(balance),raw);}for(const turns of [undefined,0,3,1.5])assert.throws(()=>createBattle({...x.config,meta:{...x.config.meta!,kitBalance:amberPowerCandidate(2)},initialTransformation:{character:'amber',scope:'turn',remainingOwnTurns:turns}}));});


test('snapshot-bearing saves use a distinct envelope rule tag; old saves retain their exact old gate',()=>{
 const currentSetup=setup('amber'),x={...currentSetup,options:{run:{...currentSetup.options.run,encounterVersion:undefined}}},cp=new BattleController({...x.config,meta:{...x.config.meta!,progressionVersion:undefined}},view,x.options).exportCheckpoint(),raw=encodeSave(cp,1,1),current=decodeSave(raw);assert.equal(current.rules,SNAPSHOT_SAVE_RULES);assert.notEqual(current.rules,SAVE_RULES);
 const oldConfig={...x.config,meta:{...x.config.meta!,progressionVersion:undefined,kitBalance:undefined}},old=new BattleController(oldConfig,view,x.options).exportCheckpoint(),oldRaw=encodeSave(old,1,1);assert.equal(decodeSave(oldRaw).rules,SAVE_RULES);assert.equal(encodeSave(decodeSave(oldRaw).checkpoint,1,1),oldRaw);
 // Recomputed checksums cannot disguise a snapshot as the old client ruleset.
 const retag=(text:string,rules:string)=>{const {checksum:_checksum,...body}=JSON.parse(text);body.rules=rules;const textBody=JSON.stringify(body);let hash=0x811c9dc5;for(let i=0;i<textBody.length;i++){hash^=textBody.charCodeAt(i);hash=Math.imul(hash,0x01000193);}return JSON.stringify({...body,checksum:(hash>>>0).toString(16).padStart(8,'0')});};
 assert.throws(()=>decodeSave(retag(raw,SAVE_RULES)));assert.throws(()=>decodeSave(retag(oldRaw,SNAPSHOT_SAVE_RULES)));
});
