import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
import {boardSkillName,boardInformation,currentBoardInformation,formInformation,currentFormInformation} from '../src/next/ui/kitInformation.ts';
import {createProfile,freezeRunMeta} from '../src/next/meta/profile.ts';import {prepareDeparture} from '../src/next/meta/departure.ts';import {rosterIds} from '../src/next/meta/roster.ts';import type {RosterId} from '../src/next/meta/roster.ts';import {kitBoardCatalog} from '../src/next/core/kitBoards.ts';import type {BoardSkillId} from '../src/next/core/types.ts';import {LEGACY_KIT_BALANCE,amberPowerCandidate} from '../src/next/meta/kitBalance.ts';
function config(id:RosterId){const p=createProfile(1);p.ownedCharacters=[...rosterIds];return prepareDeparture(freezeRunMeta(p,id,false),1).config;}
test('all current home forms equal the actual new-departure description',()=>{for(const id of rosterIds)assert.equal(currentFormInformation(id),formInformation(config(id)),id);});
test('Amber description follows legacy Red reuse, saved gauge-only, and one/two-turn power separately',()=>{const c=config('amber');assert.match(formInformation({...c,meta:{...c.meta!,kitVersion:undefined,kitBalance:undefined}}),/赤の変化.*追加投入を2回/);assert.doesNotMatch(formInformation({...c,meta:{...c.meta!,kitVersion:undefined}}),/ダメージ×|ゲージ獲得×/);assert.match(formInformation({...c,meta:{...c.meta!,kitBalance:LEGACY_KIT_BALANCE}}),/ゲージ獲得×2。ダメージは変わりません/);for(const n of [1,2] as const)assert.match(formInformation({...c,meta:{...c.meta!,kitBalance:amberPowerCandidate(n)}}),new RegExp(`手番を含む${n}自手番はリンクダメージ×2`));});
test('saved costs and form amounts override today defaults in text',()=>{const c=config('red'),b=structuredClone(c.meta!.kitBalance!);(b.boards['red-capture'] as {hp:number}).hp=4;(b as {silverBarrier:number}).silverBarrier=17;(b as {mintShapeBonus:number}).mintShapeBonus=7;const d=boardInformation({...c,meta:{...c.meta!,kitBalance:b}},'red-capture');assert.match(d,/自HP4を先に支払い生存時だけ/);assert.match(d,/ゲージ0・HP4/);assert.doesNotMatch(d,/自HP2/);for(const [id,text] of [['silver','バリアを17'],['mint','ダメージ＋7']] as const){const x=config(id);assert(formInformation({...x,meta:{...x.meta!,characterRevision:undefined,kitBalance:b}}).includes(text));}});
test('Imashiru, guardian, assassin and targeting information includes confirmed limits',()=>{assert.match(currentFormInformation('imashiru'),/今の自手番が終わるまで/);assert.match(currentFormInformation('imashiru'),/2倍。複数でも重複しません/);assert.match(currentFormInformation('imashiru'),/ゲージ200・上限300/);assert.match(boardInformation(config('imashiru'),'imashiru-insight'),/投入成功まで保持/);assert.match(currentFormInformation('silver'),/毒・トゲ・自己コスト・投入不能は防ぎません/);assert.match(currentFormInformation('violet'),/どく・げきどく以外.*ランダム.*1個.*相手手番終了まで被ダメージなし/);assert.match(boardInformation(config('silver'),'silver-freeze'),/未凍結の敵箱/);assert.match(currentBoardInformation('silver-freeze'),/未凍結の敵箱/);assert.match(currentBoardInformation('violet-poison'),/どく・げきどく以外の敵箱/);for(const id of Object.keys(kitBoardCatalog) as BoardSkillId[])assert.equal(currentBoardInformation(id),boardInformation(config('violet'),id));});
test('the actual main event logger uses the true name for every board skill',()=>{const source=readFileSync(new URL('../src/next/main.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('main.ts',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='describe');assert(node);const code=ts.transpileModule(node.getText(ast)+'\nreturn describe;',{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;const describe=new Function('boardSkillName',code)(boardSkillName);for(const id of ['pain-shared','ember','imashiru-insight',...Object.keys(kitBoardCatalog)] as BoardSkillId[])assert.equal(describe({type:'board-skill',actor:'player',skillId:id}),boardSkillName(id)+'を使用');});
test('home and active-run presentation route through their distinct information sources',()=>{const home=readFileSync(new URL('../src/next/meta/home.ts',import.meta.url),'utf8'),main=readFileSync(new URL('../src/next/main.ts',import.meta.url),'utf8');assert(home.includes('currentFormInformation(departure.rosterId)'));assert(main.includes('boardSkillName'));assert(main.includes('openBattleLog'));assert(!main.includes('固有キット v'));assert(home.includes('残り ${lv.allocatable} pt'));assert(home.includes('preparationSkillCard(id,'));});
