import test from 'node:test';
import assert from 'node:assert/strict';
import { applyAction, createBattle, battleFixtures as nextFixtures, createPlayerBuild, createSkill, createTuning, needsTurnStart, playerPower } from '../src/next/core/index.ts';
import { applyAction as legacyAction, createBattle as legacyCreate, battleFixtures } from '../src/core/index.ts';
import { getDropOptions } from '../src/next/core/board.ts';
import { linkGaugeGain } from '../src/next/core/gauge.ts';
import { trialFixture, createTrialConfig } from '../src/next/config.ts';
import { BattleController } from '../src/next/app/BattleController.ts';
import { applyRunReward, generateCategoryOffer, rewardSeed } from '../src/next/app/rewards.ts';
import type { BattleState, Resolution } from '../src/next/core/types.ts';
const opts = { run: { mode: 'endless' as const, rewards: true, rewardMode: 'categories' as const } };
const drop = (s:BattleState,col:number)=>applyAction(s,{type:'drop',candidateId:`ceiling:${col}:0`});
function make(config=trialFixture('reward','blue','marujiro',1,'manual')) { const resolutions:Resolution[]=[];const c=new BattleController(config,{render(){},async animate(r){resolutions.push(r);}},opts);return {c,resolutions}; }
async function won(seed=1){const h=make(trialFixture('reward','blue','marujiro',seed,'manual'));await h.c.drop('ceiling:2:0');return h;}
test('next omitted strategy preserves every original fixture state/event trace',()=>{
 for(const f of battleFixtures){let a=legacyCreate(f),b=createBattle(nextFixtures.find(x=>x.id===f.id)!);for(let i=0;i<30&&!a.result;i++){
 const legal=getDropOptions(b).filter(x=>x.available);const action=b.actor==='enemy'?{type:'enemy' as const}:legal.length?{type:'drop' as const,candidateId:legal[i%legal.length]!.id}:{type:'skip' as const};
 const x=legacyAction(a,action),y=applyAction(b,action);assert.deepEqual(y,x);a=x.state;b=y.state;if(!x.accepted)break;}}
});
test('manual transform pays once with no action clock, charge, RNG, box, or enemy change',()=>{const s=createBattle(trialFixture('charged','blue','marujiro',7,'manual'));const r=applyAction(s,{type:'transform'});assert.ok(r.accepted);assert.equal(r.state.gauge,0);assert.equal(r.state.actor,'player');assert.equal(r.state.turn,s.turn);assert.equal(r.state.rngState,s.rngState);assert.deepEqual(r.state.boxes,s.boxes);assert.deepEqual(r.state.hp,s.hp);assert.deepEqual(r.resolution!.events.map(e=>e.type),['transformation']);assert.equal(applyAction(r.state,{type:'transform'}).accepted,false);});
test('manual activation rejects insufficient, enemy, automatic, ended, and already transformed states atomically',()=>{
 const s=createBattle(trialFixture('charged','blue','marujiro',1,'manual'));
 const cases=[createBattle(createTrialConfig()),{...s,actor:'enemy' as const},{...s,result:{winner:'player' as const,reason:'hp-zero' as const}},createBattle(trialFixture('charged','blue','marujiro',1,'automatic')), {...s,transformation:{character:'blue' as const,scope:'stage' as const}}];
 for(const before of cases){const r=applyAction(before,{type:'transform'});assert.equal(r.accepted,false);assert.deepEqual(r.state,before);}
});
test('Red manual start does not insert now, then grants exactly two later starts',()=>{
 let s=createBattle(trialFixture('charged','red','marujiro',1,'manual'));s=applyAction(s,{type:'transform'}).state;assert.equal(needsTurnStart(s),false);assert.equal(s.boxes.length,0);
 s=drop(s,0).state;s=applyAction(s,{type:'enemy'}).state;assert.ok(needsTurnStart(s));const start=applyAction(s,{type:'start-turn'});assert.equal(start.resolution!.events.filter(e=>e.type==='drop').length,1);s=start.state;assert.equal(s.transformation?.character==='red'&&s.transformation.remainingStarts,1);
 s=drop(s,1).state;s=applyAction(s,{type:'enemy'}).state;s=applyAction(s,{type:'start-turn'}).state;assert.equal(s.transformation?.character==='red'&&s.transformation.remainingStarts,0);assert.equal(applyAction(s,{type:'transform'}).accepted,false);s=drop(s,2).state;assert.equal(s.transformation,null);
});
test('manual mode six-link charges but never activates automatically; old mode still activates',()=>{
 for(const mode of ['manual','automatic'] as const){const c=trialFixture('charged','blue','marujiro',1,mode);const s=createBattle({...c,initialBoxes:[0,1,2,3,4].map(col=>({id:`p${col}`,row:7,col,owner:'player' as const,type:'normal' as const,status:'normal' as const}))});const r=drop(s,5);assert.equal(!!r.state.transformation,mode==='automatic');const charge=r.resolution!.events.find(e=>e.type==='gauge'&&e.source==='link');assert.equal(charge?.type==='gauge'&&charge.amount,mode==='manual'?30:24);}
});
test('band gains distinguish exactly five from six-plus and honor tuning and cap',()=>{const s=createBattle(createTrialConfig());assert.deepEqual([2,3,4,5,6,7,8].map(n=>linkGaugeGain(s,n)),[0,2,4,6,30,30,30]);const custom=createBattle({...s.config,tuning:createTuning({gauge:{bands:{3:1,4:2,5:3,sixPlus:9}}})});assert.equal(linkGaugeGain(custom,8),9);assert.throws(()=>createBattle({...s.config,tuning:createTuning()}));});
test('victory first freezes category choice and pauses all stage work',async()=>{const {c}=await won();assert.equal(c.runSnapshot!.stage,1);assert.equal(c.runSnapshot!.offer!.category,'pending');assert.deepEqual(c.runSnapshot!.offer!.choices,[]);assert.equal(await c.chooseReward(c.runSnapshot!.offer!.id,'max-health'),false);assert.equal(await c.transform(),false);assert.equal(await c.chooseReward(c.runSnapshot!.offer!.id,null),false);assert.equal(c.runSnapshot!.stage,1);});
test('category cannot change and stat offers are three distinct saved members',async()=>{const {c}=await won();const id=c.runSnapshot!.offer!.id;assert.equal(await c.chooseCategory(id,'stats'),true);const offer=c.runSnapshot!.offer;assert.equal(offer!.choices.length,3);assert.equal(new Set(offer!.choices).size,3);assert.ok(offer!.choices.every(x=>['max-health','three-polish','four-polish','five-polish'].includes(x)));assert.equal(await c.chooseCategory(id,'skills'),false);assert.equal(await c.chooseCategory(id,'stats'),false);await c.start();assert.deepEqual(c.runSnapshot!.offer,offer);assert.equal(await c.chooseReward(id,'health'),false);});
test('skill candidates use only current formal pool, exclude owned plus, and keep duplicate upgrade rules',()=>{const build={...createPlayerBuild('blue'),fixed:createSkill('health',2)};for(let seed=0;seed<30;seed++){const r=generateCategoryOffer(build,seed,'id','skills');assert.equal(r.offer.choices.length,3);assert.equal(new Set(r.offer.choices).size,3);assert.ok(!r.offer.choices.includes('health'));assert.ok(r.offer.choices.every(id=>!/^A|^B|^D/.test(id)&&!id.includes('polish')&&id!=='max-health'));assert.deepEqual(r,generateCategoryOffer(build,seed,'id','skills'));}});
test('immediate recovery commits category once and carries bounded HP without combat reflection',async()=>{const config=trialFixture('reward','blue','marujiro',1,'manual');const {c,resolutions}=make({...config,initialTransformation:{character:'blue',scope:'stage'}});await c.drop('ceiling:2:0');const gauge=c.snapshot.gauge, events=resolutions.length;const id=c.runSnapshot!.offer!.id;assert.equal(await c.chooseCategory(id,'heal'),true);assert.equal(c.runSnapshot!.stage,2);assert.equal(c.snapshot.hp.player.current,28);assert.equal(c.snapshot.hp.enemy.current,40);assert.equal(c.snapshot.gauge,gauge);assert.equal(resolutions.length,events);assert.equal(c.snapshot.transformation,null);assert.equal(await c.chooseCategory(id,'heal'),false);});
test('max HP increases current HP too, persists through next stage, and resets with run',async()=>{let seed=0;while(!generateCategoryOffer(createPlayerBuild('blue'),rewardSeed(seed),'i','stats').offer.choices.includes('max-health'))seed++;const {c}=await won(seed);const id=c.runSnapshot!.offer!.id;await c.chooseCategory(id,'stats');await c.chooseReward(id,'max-health');assert.deepEqual(c.snapshot.hp.player,{max:35,current:23});assert.equal(c.snapshot.config.combatants.player.maxHp,35);await c.restart();assert.deepEqual(c.snapshot.hp.player,{max:30,current:18});});
test('run reward arithmetic heals only to cap and new power tiers stay independent',async()=>{const {c}=await won();const s=c.snapshot;assert.deepEqual(applyRunReward({...s,hp:{...s.hp,player:{max:30,current:29}}},'immediate-heal')!.hp.player,{max:30,current:30});assert.deepEqual(applyRunReward({...s,hp:{...s.hp,player:{max:30,current:30}}},'max-health')!.hp.player,{max:35,current:35});const four=applyRunReward(s,'four-polish')!;assert.equal(playerPower(four,4),9);assert.equal(playerPower(four,3),4);assert.equal(playerPower(four,5),11);const five=applyRunReward(four,'five-polish')!;assert.equal(playerPower(five,5),14);assert.equal(playerPower(five,4),9);assert.equal(applyRunReward(createBattle(createTrialConfig()),'immediate-heal'),null);});
test('skill replacement cancellation and invalid replacement preserve committed candidates and fixed slot',async()=>{const base=trialFixture('reward','blue','marujiro',1,'manual');const build={...createPlayerBuild('blue'),slots:[createSkill('first-guard'),createSkill('charge')] as const};const {c}=make({...base,initialBuild:build});await c.drop('ceiling:2:0');const id=c.runSnapshot!.offer!.id;await c.chooseCategory(id,'skills');const offer=c.runSnapshot!.offer!;const pick=offer.choices.find(x=>!['health','first-guard','charge'].includes(x));assert.ok(pick);assert.equal(await c.chooseReward(id,pick),false);assert.equal(await c.chooseReward(id,pick,9),false);assert.deepEqual(c.runSnapshot!.offer,offer);assert.equal(await c.chooseReward(id,pick,0),true);assert.equal(c.snapshot.build!.fixed.id,'health');assert.equal(c.snapshot.build!.slots[0]!.id,pick);});
test('reward categories do not perturb combat RNG and stale offers cannot change restarted run',async()=>{const a=await won(7),b=await won(7);const id=a.c.runSnapshot!.offer!.id;await a.c.chooseCategory(id,'stats');await a.c.chooseReward(id,null);await b.c.chooseCategory(b.c.runSnapshot!.offer!.id,'heal');assert.equal(a.c.snapshot.rngState,b.c.snapshot.rngState);await a.c.restart();const before=a.c.snapshot;assert.equal(await a.c.chooseReward(id,'max-health'),false);assert.equal(await a.c.chooseCategory(id,'heal'),false);assert.deepEqual(a.c.snapshot,before);});
test('manual transform input is locked during animation, and restart cancels its stale completion',async()=>{let release!:()=>void;const c=new BattleController(trialFixture('charged','red','marujiro',1,'manual'),{render(){},animate:()=>new Promise<void>(r=>{release=r;})},opts);const pending=c.transform();assert.equal(await c.transform(),false);assert.equal(await c.drop('ceiling:0:0'),false);assert.equal(c.snapshot.gauge,0);await c.restart(createTrialConfig());release();await pending;assert.equal(c.snapshot.transformation,null);assert.equal(c.snapshot.boxes.length,0);assert.equal(c.snapshot.gauge,0);});
test('Red activation then ordinary victory carries both future starts only after reward',async()=>{const base=trialFixture('reward','red','marujiro',1,'manual');const {c,resolutions}=make({...base,initialGauge:100});await c.transform();await c.drop('ceiling:2:0');assert.equal(c.runSnapshot!.status,'reward');assert.equal(c.snapshot.transformation?.character==='red'&&c.snapshot.transformation.remainingStarts,2);const count=resolutions.length;await c.chooseCategory(c.runSnapshot!.offer!.id,'heal');assert.equal(c.runSnapshot!.stage,2);assert.equal(c.snapshot.transformation?.character==='red'&&c.snapshot.transformation.remainingStarts,1);assert.equal(resolutions.slice(count).filter(r=>r.events.some(e=>e.type==='turn-start')).length,1);assert.equal(c.snapshot.actor,'player');});

import { readFileSync } from 'node:fs';
import { parityCases as nextParityCases } from './helpers/nextParityCases.ts';
test('next automatic legacy profile preserves all102 frozen release traces',()=>{const reference=JSON.parse(readFileSync(new URL('./fixtures/default-v1-parity.json',import.meta.url),'utf8'));assert.deepEqual(nextParityCases(),reference.cases);});
