import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createBattle,applyAction} from '../src/next/core/index.ts';
import {createTrialConfig} from '../src/next/config.ts';
import {forecastAction,emberForecastText} from '../src/next/ui/actionForecast.ts';
import type {Box} from '../src/next/core/types.ts';
const cast={type:'board-skill',skillId:'ember'} as const;
function state(count:number,hp=30){const c=createTrialConfig('red');const boxes:Box[]=Array.from({length:count},(_,i)=>({id:`enemy${i}`,row:7,col:i,owner:'enemy',type:i===0?'poison':'normal',status:'normal'}));return createBattle({...c,initialBoxes:boxes,combatants:{...c.combatants,player:{...c.combatants.player,initialHp:hp}}});}
test('Ember count comes from actual committed conversion events, not a maximum or random guess',()=>{for(const count of [0,1,2,4]){const s=state(count),before=JSON.stringify(s),result=applyAction(s,cast),view=forecastAction(s,cast)!;assert.equal(view.conversions,result.resolution!.events.filter(e=>e.type==='boxes-converted').reduce((n,e)=>n+e.boxIds.length,0));assert.equal(JSON.stringify(s),before);assert.deepEqual(applyAction(s,cast),result);assert.match(emberForecastText(view).primary,new RegExp(`敵箱${view.conversions}個`));if(count===0){assert.match(emberForecastText(view).secondary,/対象なし.*HPと1手/);assert.equal(emberForecastText(view).confirm,'対象なしで使う');}else assert.match(emberForecastText(view).secondary,/ランダム変換.*1手消費.*リンクは発動しません/);}});
test('self-KO explicitly predicts defeat before any conversion and remains the same legal action',()=>{const s=state(3,3),r=applyAction(s,cast),v=forecastAction(s,cast)!;assert(r.accepted);assert.equal(v.conversions,0);assert.equal(v.result,'loss');assert.match(emberForecastText(v).primary,/敗北/);assert.match(emberForecastText(v).secondary,/敗北 · 変換なし/);assert.equal(emberForecastText(v).confirm,'敗北を承知で使う');});
test('unowned art is faded independently of readable badges and preview controls',()=>{const home=readFileSync(new URL('../src/next/meta/home.ts',import.meta.url),'utf8'),css=readFileSync(new URL('../src/next/meta/home.css',import.meta.url),'utf8');assert.match(home,/ownership-badge[^>]*>🔒 未所持/);assert.match(home,/能力・立ち絵をプレビュー/);assert.match(css,/\.is-unowned img\{opacity:\.32/);assert.match(css,/\.home-hero\.is-unowned \.home-character\{opacity:\.35/);assert.match(css,/ownership-badge[^}]*color:#fff/);assert.doesNotMatch(css,/is-unowned[^}]*pointer-events:none/);});
test('conversion result badge reports actual count and Ember preview does not truncate warning text',()=>{const cue=readFileSync(new URL('../src/next/ui/boardSkillPresentation.ts',import.meta.url),'utf8'),css=readFileSync(new URL('../src/next/style.css',import.meta.url),'utf8');assert.match(cue,/敵箱\$\{cue.targets.length\}個 → 自箱/);assert.match(css,/row-forecast\) small\{white-space:normal;overflow:visible;text-overflow:clip/);});

test('Blue readout explains actual box ownership damage and keeps empty-row action legal',()=>{const main=readFileSync(new URL('../src/next/main.ts',import.meta.url),'utf8');assert.match(main,/'痛みはお互いに'/);assert.match(main,/自箱\$\{row.playerCount\}個→敵−\$\{row.enemyDamage\}/);assert.match(main,/敵箱\$\{row.enemyCount\}個→自−\$\{row.playerDamage\}/);assert.match(main,/空の行です · 効果なしでも1手消費/);assert.match(main,/落下でリンクは発動しません/);});
