import {createTuning} from '../src/next/core/tuning.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,applyAction,defaultConfig,createSkill} from '../src/next/core/index.ts';
import {createTrialConfig} from '../src/next/config.ts';
import {resolvePoisonTurnEnd,settleBoxTypes,frozenPenalty} from '../src/next/core/boxTypes.ts';
import {createProfile,freezeRunMeta} from '../src/next/meta/profile.ts';
import {prepareDeparture} from '../src/next/meta/departure.ts';
import {BattleController} from '../src/next/app/BattleController.ts';
import {encodeSave,decodeSave} from '../src/next/app/saveCheckpoint.ts';
import {forecastAction} from '../src/next/ui/actionForecast.ts';
import {actionBreakdown} from '../src/next/ui/battleReadability.ts';
import {feedbackForEvent} from '../src/next/ui/battleFeedback.ts';
import type {Box} from '../src/next/core/types.ts';
const b=(row:number,col:number,type:Box['type']='normal',owner:Box['owner']='player'):Box=>({id:`${row}:${col}`,row,col,type,owner,status:'normal'});
const high={...defaultConfig.combatants.player,maxHp:1000,initialHp:1000};
test('one box has one enum type; Imashiru assignment overwrites poison, frozen and rubble',()=>{const p=createProfile();p.ownedCharacters.push('imashiru');const x=prepareDeparture(freezeRunMeta(p,'imashiru',false),1);const s=createBattle({...x.config,initialGauge:200,initialBoxes:[b(7,0,'poison'),b(7,1,'frozen'),b(7,2,'rubble'),b(7,3,'deadly-poison','enemy')]});const r=applyAction(s,{type:'transform'});assert(r.accepted);assert(r.state.boxes.filter(b=>b.owner==='player').every(b=>b.type==='shiny'));assert.equal(r.state.boxes.find(b=>b.owner==='enemy')!.type,'deadly-poison');assert.equal(resolvePoisonTurnEnd(r.state,'player').events.length,0);});
test('frozen subtracts1 per participating box from a complete link and clamps damage at zero',()=>{const base=createTrialConfig('red');const s=createBattle({...base,initialBuild:{fixed:createSkill('grow-fire'),slots:[null,null],power:{3:0,4:0,5:0}},combatants:{...base.combatants,player:{...base.combatants.player,attacks:{3:1,4:1,5:1}}},initialBoxes:[b(7,0,'frozen'),b(7,1,'frozen')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:2:0'});const e=r.resolution!.events.find(e=>e.type==='attack')!;assert.equal(e.damage,0);assert.equal(frozenPenalty(s.boxes,['7:0','7:1','missing']),2);});
test('shiny doubles once before frozen subtraction; unrelated frozen does not penalize',()=>{const base=createTrialConfig('blue'),s=createBattle({...base,initialBoxes:[b(7,0,'shiny'),b(7,1,'frozen'),b(7,5,'frozen')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.resolution!.events.find(e=>e.type==='attack')!.damage,7);const g=r.resolution!.events.find(e=>e.type==='gauge'&&e.source==='link')!;assert(g.type==='gauge');assert.equal(g.amount,4);});
test('poison and deadly poison apply1 and2 per owned box exactly at that owner turn end; neutral does nothing',()=>{const s=createBattle({...createTrialConfig('red'),initialBoxes:[b(7,0,'poison'),b(7,1,'deadly-poison'),b(7,2,'poison','enemy'),b(7,3,'deadly-poison','neutral')]});const p=resolvePoisonTurnEnd(s,'player'),e=resolvePoisonTurnEnd(s,'enemy');assert.equal(p.state.hp.player.current,s.hp.player.current-3);assert.equal(p.state.hp.enemy.current,s.hp.enemy.current);assert.equal(p.state.gauge,s.gauge+3);assert.equal(e.state.hp.enemy.current,s.hp.enemy.current-1);assert.equal(e.state.gauge,s.gauge);assert.equal(p.events.filter(e=>e.type==='type-damage').length,1);});
test('ordinary action ticks poison, transformation and Red bonus insertion do not',()=>{const base=createTrialConfig('red');const s=createBattle({...base,initialGauge:100,initialBoxes:[b(7,5,'deadly-poison')]});const transformed=applyAction(s,{type:'transform'});assert.equal(transformed.state.hp.player.current,s.hp.player.current);const ordinary=applyAction(transformed.state,{type:'drop',candidateId:'ceiling:0:0'});assert.equal(ordinary.resolution!.events.filter(e=>e.type==='type-damage').length,1);const enemy=applyAction(ordinary.state,{type:'enemy'}).state;const bonus=applyAction(enemy,{type:'start-turn'});assert(bonus.accepted);assert.equal(bonus.resolution!.events.filter(e=>e.type==='type-damage').length,0);});
test('enemy multi-insertion turn has one poison tick, not one per drop',()=>{const base=createTrialConfig('blue','mother-core');const s=createBattle({...base,firstActor:'enemy',initialEnemyTurnCount:5,combatants:{player:high,enemy:high},initialBoxes:[b(7,0,'deadly-poison','enemy')]});const r=applyAction(s,{type:'enemy'});assert(r.accepted);assert.equal(r.resolution!.events.filter(e=>e.type==='drop').length,2);assert.equal(r.resolution!.events.filter(e=>e.type==='type-damage').length,1);assert.equal(r.state.hp.enemy.current,998);});
test('poison after a winning player attack produces simultaneous-KO loss, charging only actualHP lost',()=>{const base=createTrialConfig('red'),s=createBattle({...base,combatants:{player:{...base.combatants.player,initialHp:1},enemy:{...base.combatants.enemy,initialHp:1}},initialBoxes:[b(7,0),b(7,1),b(7,5,'deadly-poison')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.state.result!.winner,'enemy');assert.equal(r.state.hp.player.current,-1);assert(r.state.hp.enemy.current<=0);const damageG=r.resolution!.events.filter(e=>e.type==='gauge'&&e.source==='damage');assert.equal(damageG.length,1);assert.equal(damageG[0]!.type==='gauge'&&damageG[0]!.amount,1);});
test('poison on an enemy can finish a stage at enemy turn end',()=>{const base=createTrialConfig('blue'),s=createBattle({...base,firstActor:'enemy',combatants:{...base.combatants,enemy:{...base.combatants.enemy,initialHp:1}},initialBoxes:[b(7,0,'poison','enemy')]});const r=applyAction(s,{type:'enemy'});assert.equal(r.state.result!.winner,'player');});
test('conversion changes which owner poison harms, while preserving its single type',()=>{const s=createBattle({...createTrialConfig('red'),initialBoxes:[b(7,0,'deadly-poison','enemy')]});const r=applyAction(s,{type:'board-skill',skillId:'ember'});const converted=r.state.boxes[0]!;assert.equal(converted.owner,'player');assert.equal(converted.type,'deadly-poison');assert.equal(r.state.hp.player.current,s.hp.player.current-3-2);});
test('rubble waits under one box, crushes under two, and passive cascade preserves type/ownership without links',()=>{const board={...defaultConfig.board,width:1,height:6};const first=settleBoxTypes(board,[b(5,0,'rubble'),b(4,0)]);assert.equal(first.crushed.length,0);const cascaded=settleBoxTypes(board,[b(5,0,'rubble'),b(4,0,'rubble'),b(3,0),b(2,0,'frozen')]);assert.deepEqual(cascaded.crushed,['5:0','4:0']);assert.equal(cascaded.boxes.length,2);assert.equal(cascaded.boxes[0]!.row,5);assert.equal(cascaded.boxes[1]!.type,'frozen');});
test('rubble removal occurs after active attacks and never adds passive attacks or heals',()=>{const base=createTrialConfig('red');const s=createBattle({...base,initialBoxes:[b(7,0,'rubble'),b(6,0)]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:0:0'});assert(r.accepted);const events=r.resolution!.events;assert(events.findIndex(e=>e.type==='rubble-crushed')>events.findIndex(e=>e.type==='attack'));assert.equal(events.filter(e=>e.type==='attack').length,1);assert.equal(r.state.boxes.length,2);});
test('type damage is included in forecast, hit feedback and last-action totals',()=>{const s=createBattle({...createTrialConfig('blue'),initialBoxes:[b(7,5,'poison')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:0:0'});const f=forecastAction(s,{type:'drop',candidateId:'ceiling:0:0'})!;assert.equal(f.selfLoss,1);const e=r.resolution!.events.find(e=>e.type==='type-damage')!;assert.equal(feedbackForEvent(e,[])!.text,'1ダメージ');assert.equal(actionBreakdown(r.resolution!,1).lost.player,1);});
test('types persist in checkpoint and no poison tick is replayed on restore',async()=>{const p=createProfile(),setup=prepareDeparture(freezeRunMeta(p,'blue',false),1);const c=new BattleController({...setup.config,initialBoxes:[b(7,5,'poison')]},{render(){},async animate(){}},setup.options);await c.start();await c.drop('ceiling:0:0');const cp=decodeSave(encodeSave(c.exportCheckpoint(),1)).checkpoint;const restored=BattleController.restore(cp,{render(){},async animate(){}});await restored.start();assert.deepEqual(JSON.parse(JSON.stringify(restored.snapshot)),JSON.parse(JSON.stringify(c.snapshot)));assert.equal(restored.snapshot.boxes.find(b=>b.id==='7:5')!.type,'poison');});
test('unknown types and multi-type arrays fail validation without rewriting boxes',()=>{const base=createTrialConfig('blue');for(const type of ['unknown',['shiny','poison']])assert.throws(()=>createBattle({...base,initialBoxes:[{...b(7,0),type} as unknown as Box]}));});

test('thorn hits the active inserter for floor2% maxHP, minimum1, regardless of thorn ownership',()=>{for(const owner of ['player','enemy','neutral'] as const){const base=createTrialConfig('blue'),s=createBattle({...base,initialBoxes:[b(7,0,'thorn',owner)]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:1:0'});const hit=r.resolution!.events.find(e=>e.type==='type-damage'&&e.source==='thorn')!;assert.equal(hit.type==='type-damage'&&hit.damage,1);assert.equal(hit.type==='type-damage'&&hit.target,'player');assert.equal(r.state.hp.player.current,29);}});
test('each adjacent thorn triggers once; only8 neighbors count and shiny cannot multiply it',()=>{const base=createTrialConfig('blue'),s=createBattle({...base,combatants:{...base.combatants,player:{...base.combatants.player,maxHp:123,initialHp:123}},initialBoxes:[b(7,0,'thorn'),b(7,2,'thorn','enemy'),b(7,4,'thorn','neutral'),b(7,5,'shiny')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:1:0'});const hits=r.resolution!.events.filter(e=>e.type==='type-damage'&&e.source==='thorn');assert.equal(hits.length,2);assert(hits.every(e=>e.type==='type-damage'&&e.damage===2));assert.equal(r.state.hp.player.current,119);});
test('thorn lethal damage resolves before healing/link attacks and retains PvE defeat',()=>{const base=createTrialConfig('blue'),s=createBattle({...base,combatants:{player:{...base.combatants.player,initialHp:1},enemy:{...base.combatants.enemy,initialHp:1}},initialBoxes:[b(7,0),b(7,1),b(7,3,'thorn','neutral')]});const r=applyAction(s,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.state.result!.winner,'enemy');assert.equal(r.resolution!.events.filter(e=>e.type==='attack'||e.type==='heal').length,0);assert.equal(r.state.hp.enemy.current,1);const damageG=r.resolution!.events.filter(e=>e.type==='gauge'&&e.source==='damage');assert.equal(damageG.length,1);assert.equal(damageG[0]!.type==='gauge'&&damageG[0]!.amount,1);});
test('passive falls and ownership conversion near thorns cannot create a thorn hit',()=>{const base=createTrialConfig('red'),s=createBattle({...base,initialBoxes:[b(7,0,'thorn','enemy'),b(7,1,'normal','enemy')]});const r=applyAction(s,{type:'board-skill',skillId:'ember'});assert(r.accepted);assert.equal(r.resolution!.events.filter(e=>e.type==='type-damage'&&e.source==='thorn').length,0);const settled=settleBoxTypes(s.config.board,[b(7,0,'thorn'),b(5,1)]);assert.equal(settled.boxes.find(b=>b.id==='5:1')!.row,7);});

test('thorn KO in the first MotherCore insertion stops its second insertion and yields a surviving-player win',()=>{const base=createTrialConfig('blue','mother-core'),s=createBattle({...base,board:{...base.board,width:2,height:3},tuning:createTuning({...base.tuning,bosses:{...base.tuning!.bosses,motherThresholdPercent:1}}),firstActor:'enemy',initialEnemyTurnCount:5,combatants:{player:high,enemy:{...base.combatants.enemy,maxHp:50,initialHp:2}},initialBoxes:[b(2,0,'thorn','neutral'),b(2,1,'thorn','neutral')]});const r=applyAction(s,{type:'enemy'});assert.equal(r.resolution!.events.filter(e=>e.type==='drop').length,1);assert.equal(r.state.result!.winner,'player');assert.equal(r.state.hp.player.current,1000);});

test('MotherCore crushes rubble between active insertions before deciding the board is blocked',()=>{
 const base=createTrialConfig('blue','mother-core');
 const before=createBattle({...base,board:{...base.board,width:1,height:3},firstActor:'enemy',initialEnemyTurnCount:5,combatants:{player:{...base.combatants.player,maxHp:1000,initialHp:1000},enemy:{...base.combatants.enemy,maxHp:1000,initialHp:1000}},initialBoxes:[b(2,0,'rubble','enemy'),b(1,0,'normal','enemy')]});
 const result=applyAction(before,{type:'enemy'});assert(result.accepted);
 const events=result.resolution!.events,dropIndices=events.flatMap((e,i)=>e.type==='drop'?[i]:[]),crushIndex=events.findIndex(e=>e.type==='rubble-crushed');
 assert.equal(dropIndices.length,2);assert(crushIndex>dropIndices[0]!&&crushIndex<dropIndices[1]!);
 assert.equal(events.filter(e=>e.type==='attack').length,2);assert.equal(events.filter(e=>e.type==='instant-kill').length,0);
 assert.equal(result.state.hp.player.current,990);assert.equal(result.state.result,null);assert.equal(result.state.boxes.length,3);
});

test('standard-board MotherCore second insertion uses the post-crush landing row and link length',()=>{
 const base=createTrialConfig('blue','mother-core');const before=createBattle({...base,seed:1972,firstActor:'enemy',initialEnemyTurnCount:5,combatants:{player:{...base.combatants.player,maxHp:1000,initialHp:1000},enemy:{...base.combatants.enemy,maxHp:1000,initialHp:1000}},initialBoxes:[b(7,0,'rubble','enemy'),b(6,0,'normal','enemy')]});
 const result=applyAction(before,{type:'enemy'}),events=result.resolution!.events;assert.deepEqual(events.filter(e=>e.type==='drop').map(e=>[e.box.row,e.box.col]),[[5,0],[5,0]]);assert.deepEqual(events.filter(e=>e.type==='attack').map(e=>e.damage),[5,5]);assert.equal(result.state.hp.player.current,990);assert.equal(result.state.result,null);
});

test('owner-safe-v2 thorns: same-owner thorns are harmless, orthogonal 5%, diagonal 1%, neutral hurts anyone; legacy runs keep 2% all around',async()=>{
 const {thornDamage,resolveThornInsertion}=await import('../src/next/core/boxTypes.ts');const {createBattle}=await import('../src/next/core/battle.ts');const {createTrialConfig,prepareTrialSetup}=await import('../src/next/config.ts');
 const at=(row:number,col:number,owner:'player'|'enemy'|'neutral',type:'thorn'|'normal'='thorn')=>({id:`t${row}:${col}`,row,col,owner,type,status:'normal' as const});
 const v2={...createTrialConfig('blue'),thornRule:'owner-safe-v2' as const},legacy=createTrialConfig('blue');
 const dropped=at(5,2,'player','normal');
 assert.equal(thornDamage(v2,100,at(5,3,'enemy'),dropped,'player'),5);
 assert.equal(thornDamage(v2,100,at(4,3,'enemy'),dropped,'player'),1);
 assert.equal(thornDamage(v2,100,at(5,3,'player'),dropped,'player'),0);
 assert.equal(thornDamage(v2,100,at(5,3,'neutral'),dropped,'player'),5);
 assert.equal(thornDamage(v2,30,at(5,3,'enemy'),dropped,'player'),1,'floor 1.5 → 1 (minimum 1)');
 assert.equal(thornDamage(legacy,100,at(5,3,'player'),dropped,'player'),2,'legacy: own thorns still hurt, 2%');
 // Integrated: one enemy thorn beside, one own thorn diagonal, one enemy thorn diagonal → 5 + 0 + 1.
 const s=createBattle({...v2,combatants:{...v2.combatants,player:{...v2.combatants.player,maxHp:100,initialHp:100}},initialBoxes:[at(5,3,'enemy'),at(4,1,'player'),at(4,3,'enemy')]});
 const r=resolveThornInsertion(s,dropped);assert.equal(r.state.hp.player.current,94);assert.equal(r.events.filter(e=>e.type==='type-damage').length,2);
 assert.equal(prepareTrialSetup({character:'blue',firstEnemy:'marujiro',seed:1,mode:'manual',stage:1,fixture:'normal',route:'boss-loop'}).config.thornRule,'owner-safe-v2','new runs adopt the new rule');
});
