import {trophySkillIds} from '../src/next/core/skillCatalog.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createProfile,characterGrowth,legacyLevelInfo,migrateProfile,gainCharacterXp,useXpEnergy,validateProfile,ProfileStore,freezeRunMeta,settleProfile,TREE_POINT_CAPACITY} from '../src/next/meta/profile.ts';
import type {Profile} from '../src/next/meta/profile.ts';import {rosterIds} from '../src/next/meta/roster.ts';import {createProfileImportReader} from '../src/next/meta/profileImport.ts';import {prepareDeparture} from '../src/next/meta/departure.ts';import {BattleController} from '../src/next/app/BattleController.ts';import {encodeSave,decodeSave,PROGRESSION_SAVE_RULES,LATE_SAVE_RULES} from '../src/next/app/saveCheckpoint.ts';import type {RunCheckpoint} from '../src/next/app/saveCheckpoint.ts';
const fixtures=JSON.parse(readFileSync(new URL('./fixtures/talent-legacy-site90.json',import.meta.url),'utf8')).cases as Array<{name:string;profile:Profile;checkpoint?:RunCheckpoint;terminalCheckpoint?:RunCheckpoint}>;
const full={three:5,four:5,five:5,slots:2,board:1},view={render(){},async animate(){}};
const stripped=(p:Profile)=>{const n=structuredClone(p);n.ownedSkills=n.ownedSkills.filter(id=>!trophySkillIds.includes(id as never));delete n.progressionVersion;delete n.treeVersion;delete n.boardCatalogVersion;n.schema=1;for(const c of Object.values(n.characters)){delete c.legacyLevelFloor;delete c.tree.rewardHeal;delete c.legacyPointFloor;}return n;};
test('all25 real Site90 fixtures migrate without losing XP/levels/points or any existing record',()=>{assert.equal(fixtures.length,25);for(const f of fixtures){const raw=JSON.stringify(f.profile),n=migrateProfile(f.profile);assert.equal(n.schema,2);assert.equal(n.progressionVersion,2);assert.deepEqual(stripped(n),f.profile);for(const id of rosterIds){const old=legacyLevelInfo(f.profile.characters[id].xp),g=characterGrowth(n.characters[id]);assert.equal(g.level,old.level);assert.equal(g.points,old.points);assert.equal(g.storedXp,f.profile.characters[id].xp);assert(g.allocatable>=0);}assert.equal(JSON.stringify(f.profile),raw);assert.equal(migrateProfile(n),n);validateProfile(n);}});
test('L12 has24 points; old L30 retains60 with7 reserve, including free respec and full-tree state',()=>{assert.equal(TREE_POINT_CAPACITY,29);const p=createProfile();p.characters.blue.xp=1540;const g=characterGrowth(p.characters.blue);assert.equal(g.level,12);assert.equal(g.points,24);assert.equal(g.allocatable,24);assert(g.growthAtCap&&!g.treeComplete);const old=structuredClone(p);old.schema=1;delete old.progressionVersion;old.characters.blue.xp=9280;old.characters.blue.tree=full;const n=migrateProfile(old),max=characterGrowth(n.characters.blue);assert.equal(max.level,30);assert.equal(max.points,60);assert.equal(max.reserve,7);assert.equal(max.allocatable,29);assert(!max.treeComplete&&max.growthAtCap);n.characters.blue.tree={three:0,four:0,five:0,slots:0,board:0};assert.equal(characterGrowth(n.characters.blue).allocatable,53);assert.equal(characterGrowth(n.characters.blue).reserve,7);});
test('cap-crossing energy retains full XP and cannot spend on either new or grandfathered capped characters',()=>{const p=createProfile();p.energy=2;p.characters.blue.xp=1520;const n=useXpEnergy(p,'blue');assert.equal(n.characters.blue.xp,1570);assert.equal(n.energy,1);assert.equal(characterGrowth(n.characters.blue).level,12);assert.throws(()=>useXpEnergy(n,'blue'));assert.equal(p.energy,2);const old=structuredClone(p);old.schema=1;delete old.progressionVersion;old.characters.blue.xp=9280;const migrated=migrateProfile(old);assert.equal(characterGrowth(migrated.characters.blue).level,30);assert.throws(()=>useXpEnergy(migrated,'blue'));assert.equal(migrated.energy,2);assert.throws(()=>gainCharacterXp({...p.characters.blue,xp:Number.MAX_SAFE_INTEGER},1));});
class Storage{data=new Map<string,string>();writes=0;failAt=0;mode='';getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){this.writes++;const hit=this.writes===this.failAt;if(hit&&this.mode==='before')throw Error('before');if(hit&&this.mode==='drop')return;this.data.set(k,v);if(hit&&this.mode==='after')throw Error('after');}}
test('backup-first migration survives every before/after/drop failure without recapturing floors',()=>{for(const failAt of [1,2,3])for(const mode of ['before','after','drop']){const s=new Storage(),store=new ProfileStore(s,()=>true),old=fixtures.find(f=>f.name==='legacy-xp-9280')!.profile,raw=JSON.stringify(old);s.data.set(store.key,raw);s.failAt=failAt;s.mode=mode;assert.throws(()=>store.read());const durable=s.getItem(store.key)!;assert(durable===raw||JSON.parse(durable).schema===2);s.failAt=0;const retry=new ProfileStore(s,()=>true),n=retry.read();assert.equal(s.getItem(store.key+'.before-growth-v2'),raw);assert.equal(characterGrowth(n.characters.blue).level,30);assert.equal(characterGrowth(n.characters.blue).points,60);const saved=s.getItem(store.key),writes=s.writes;retry.read();assert.equal(s.writes,writes);assert.equal(s.getItem(store.key),saved);}});
test('old active/terminal receipt raises legacy floors once; new receipts retain XP without creating legacy levels',()=>{const f=fixtures.find(x=>x.name==='legacy-active-before-cap')!,cp=f.terminalCheckpoint!,oldRaw=JSON.stringify(cp);const p=migrateProfile(f.profile),settled=settleProfile(p,cp,33);const g=characterGrowth(settled.characters.blue);assert.equal(g.storedXp,2289);assert.equal(g.level,14);assert.equal(g.points,28);assert.equal(g.reserve,0);assert.equal(settled.coins,4771);assert.equal(settleProfile(settled,cp,99),settled);assert.equal(JSON.stringify(cp),oldRaw);
 const setup=prepareDeparture(freezeRunMeta(settled,'blue',true),77),c=new BattleController(setup.config,view,setup.options),next=structuredClone(c.exportCheckpoint());settled.launches[next.runId]={character:'blue',snapshot:JSON.stringify(next.initialConfig.meta)};Object.assign(next,{run:{...next.run!,stage:50,defeatedCount:50,status:'cleared'},state:{...next.state,hp:{...next.state.hp,player:{...next.state.hp.player,current:10},enemy:{...next.state.hp.enemy,current:0}},result:{winner:'player',reason:'hp-zero'}}});const current=settleProfile(settled,next,100),nextGrowth=characterGrowth(current.characters.blue);assert.equal(nextGrowth.storedXp,3039);assert.equal(nextGrowth.level,14);assert.equal(nextGrowth.points,28);assert.equal(nextGrowth.reserve,0);assert.equal(decodeSave(encodeSave(next,1)).rules,LATE_SAVE_RULES);
});
test('legacy and new backups import with matching versions; malformed floors reject without replacing valid profile',async()=>{let candidate:Profile|null=null;const reader=createProfileImportReader(x=>{candidate=x.profile;});for(const p of [fixtures[0]!.profile,migrateProfile(fixtures[0]!.profile)]){await reader.select({size:100,text:async()=>JSON.stringify({format:'game1-profile-backup',version:p.schema,profile:p})});assert.deepEqual(candidate,p);}const storage=new Storage(),store=new ProfileStore(storage,()=>true);store.read();const raw=storage.getItem(store.key);for(const edit of [(p:Profile)=>p.characters.blue.legacyLevelFloor=30,(p:Profile)=>{p.characters.blue.legacyLevelFloor=1;p.characters.blue.legacyPointFloor=60;},(p:Profile)=>{p.characters.blue.legacyLevelFloor=31;p.characters.blue.legacyPointFloor=62;}]){const p=store.current;edit(p);assert.throws(()=>store.write(p));assert.equal(storage.getItem(store.key),raw);await reader.select({size:100,text:async()=>JSON.stringify({format:'game1-profile-backup',version:2,profile:p})});assert.equal(candidate,null);}});
test('new profile schema and new-run progression gate reject unknown future terms safely',()=>{const p=createProfile();assert.equal(p.schema,2);const x=prepareDeparture(freezeRunMeta(p,'blue',false),1);assert.equal(x.config.meta!.progressionVersion,2);const cp=new BattleController(x.config,view,x.options).exportCheckpoint();assert.equal(decodeSave(encodeSave(cp,1)).rules,LATE_SAVE_RULES);const legacy=new BattleController(x.config,view,{run:{...x.options.run,encounterVersion:undefined}}).exportCheckpoint();assert.equal(decodeSave(encodeSave(legacy,1)).rules,PROGRESSION_SAVE_RULES);const invalid=structuredClone(p) as unknown as Record<string,unknown>;invalid.progressionVersion=3;assert.throws(()=>validateProfile(invalid as unknown as Profile));});
