import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createInspectionGesture} from '../src/next/ui/boxInspection.ts';
import {boxTypeInformation} from '../src/next/ui/boxTypeInformation.ts';
import {boxTypeOverlay,energyBoxMarkup} from '../src/next/ui/energyBox.ts';
import {boxTypeIds,frozenLinkAmount} from '../src/next/core/boxTypes.ts';
import {createBattle,applyAction,createSkill} from '../src/next/core/index.ts';
import {createTrialConfig,prepareTrialSetup} from '../src/next/config.ts';
import {forecastAction} from '../src/next/ui/actionForecast.ts';
import {createNextStageConfig} from '../src/next/app/BattleRun.ts';
import type {Box} from '../src/next/core/types.ts';
const b=(col:number,type:Box['type']='normal',row=7):Box=>({id:`${row}:${col}`,row,col,type,owner:'player',status:'normal'});
const base=()=>createTrialConfig('blue');
test('tap, consumed hold, movement, cancellation and new gesture remain distinct',()=>{const g=createInspectionGesture();assert(g.start(1,10,10));g.end(1);assert(!g.blocks());g.start(2,10,10);g.consume();g.end(2);assert(g.blocks());assert(g.start(3,10,10));assert(!g.blocks());assert(g.move(3,20,10));g.end(3);assert(g.blocks());g.reset();assert(g.blocks());assert(g.start(9,0,0));assert(!g.blocks());});
test('all fingers must lift before a new valid gesture after multitouch',()=>{const g=createInspectionGesture();assert(g.start(1,0,0));assert(!g.start(2,0,0));g.end(1);assert(!g.start(3,0,0));g.end(2);g.end(3);assert(g.blocks());assert(g.start(4,0,0));assert(!g.blocks());});
test('all eight types have full names and distinct non-letter visual overlays',()=>{const state=createBattle(base());for(const type of boxTypeIds){const box=b(0,type),info=boxTypeInformation(box,state),svg=energyBoxMarkup(box,{characterId:'blue'});assert(info.name);assert(info.effect);assert.match(svg,/<circle class="eb-core-fill"/);assert.doesNotMatch(svg,/<text|eb-type-mark/);if(type==='normal'){assert.equal(boxTypeOverlay(type),'');assert.match(info.effect,/追加効果はありません/);}else{assert.match(svg,new RegExp(`eb-type-${type}`));assert(svg.indexOf('eb-type-overlay')>svg.indexOf('eb-energy-float'));}}assert.equal(new Set(boxTypeIds.map(boxTypeOverlay)).size,8);});
test('new-rule half once, odd flooring, count independence, unrelated boxes and legacy subtraction',()=>{for(const power of [1,3,5,8,13])for(const count of [1,2]){const state=createBattle({...base(),frozenRule:'half-melt-v1',initialBoxes:[b(0,'frozen'),b(1,count===2?'frozen':'normal')]});assert.equal(frozenLinkAmount(state,['7:0','7:1'],power),Math.floor(power/2));assert.equal(frozenLinkAmount(state,['missing'],power),power);assert.equal(frozenLinkAmount({...state,config:base()},['7:0','7:1'],power),Math.max(0,power-count));}});
test('3/4/5 links, shiny before frozen and forecast/live parity',()=>{for(const length of [3,4,5])for(const shiny of [false,true]){const boxes=Array.from({length:length-1},(_,col)=>b(col,col===0?'frozen':shiny&&col===1?'shiny':'normal'));const state=createBattle({...base(),frozenRule:'half-melt-v1',initialBoxes:boxes});const action={type:'drop' as const,candidateId:`ceiling:${length-1}:0`};const live=applyAction(state,action),preview=forecastAction(state,action)!;assert(live.accepted);const hit=live.resolution!.events.find(e=>e.type==='attack')!;const original=applyAction({...state,boxes:boxes.map(box=>({...box,type:box.type==='frozen'?'normal':box.type}))},action).resolution!.events.find(e=>e.type==='attack')!;assert.equal(hit.damage,Math.floor(original.damage/2));assert.equal(preview.damage,hit.damage);}});
test('new frozen rule never changes shape damage or shape healing',()=>{const config={...base(),initialBuild:{fixed:createSkill('health'),slots:[createSkill('square-strike'),null] as const,power:{3:0,4:0,5:0}},initialBoxes:[b(1,'frozen',6),b(0,'frozen'),b(1)]};const old=applyAction(createBattle(config),{type:'drop',candidateId:'ceiling:0:0'}),fresh=applyAction(createBattle({...config,frozenRule:'half-melt-v1'}),{type:'drop',candidateId:'ceiling:0:0'});const shapes=(r:typeof old)=>r.resolution!.events.filter(e=>e.type==='damage'&&e.source==='square-strike'||e.type==='heal');assert(shapes(fresh).length>0);assert.deepEqual(shapes(fresh),shapes(old));});
test('new starts carry rule into later stages; legacy absence is preserved',()=>{const x=prepareTrialSetup({character:'blue',firstEnemy:'marujiro',seed:1,mode:'manual',stage:1,fixture:'normal',route:'boss-loop'});assert.equal(x.config.frozenRule,'half-melt-v1');for(const config of [x.config,base()]){const s=createBattle(config),won={...s,result:{winner:'player' as const,reason:'hp-zero' as const}};const next=createNextStageConfig(config,won,'marujiro',2);assert.equal(next.frozenRule,config.frozenRule);const info=boxTypeInformation(b(0,'frozen'),s);assert.match(info.effect,config.frozenRule?/半減/:/旧ルール/);}});
test('inspection integration resets armed actions and offers keyboard/toggle routes',()=>{const main=readFileSync(new URL('../src/next/main.ts',import.meta.url),'utf8'),ui=readFileSync(new URL('../src/next/ui/boxInspection.ts',import.meta.url),'utf8');assert.match(main,/clearSelection:\(\)=>\{rowDoubleTap.reset\(\);selected=null/);assert.match(ui,/450/);assert.match(ui,/aria-pressed/);assert.match(ui,/shiftKey/);assert.match(ui,/dialog.addEventListener\('cancel'/);assert.match(ui,/closeButton.onclick=close/);});

test('frozen thaws only after a qualifying attack, while absolute-zero persists',()=>{for(const type of ['frozen','absolute-zero'] as const){const state=createBattle({...base(),frozenRule:'half-melt-v1',initialBoxes:[b(0,type),b(1)]});const r=applyAction(state,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.resolution!.events.find(e=>e.type==='attack')!.damage,2);assert.equal(r.state.boxes.find(x=>x.id==='7:0')!.type,type==='frozen'?'normal':'absolute-zero');const thaw=r.resolution!.events.findIndex(e=>e.type==='boxes-thawed');if(type==='frozen')assert(thaw>r.resolution!.events.findIndex(e=>e.type==='attack'));else assert.equal(thaw,-1);const incomplete=applyAction(createBattle({...base(),frozenRule:'half-melt-v1',initialBoxes:[b(0,type)]}),{type:'drop',candidateId:'ceiling:1:0'});assert.equal(incomplete.state.boxes.find(x=>x.id==='7:0')!.type,type);}});
test('mixed frozen/absolute-zero halves once, melts only frozen, and legacy never melts',()=>{for(const rule of ['half-melt-v1',undefined] as const){const state=createBattle({...base(),frozenRule:rule,initialBoxes:[b(0,'frozen'),b(1,rule?'absolute-zero':'normal')]});const r=applyAction(state,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.resolution!.events.find(e=>e.type==='attack')!.damage,rule?2:3);assert.equal(r.state.boxes.find(x=>x.id==='7:0')!.type,rule?'normal':'frozen');if(rule)assert.equal(r.state.boxes.find(x=>x.id==='7:1')!.type,'absolute-zero');}});
test('inspection footer has an explicit third column and bounded height, including expanded forecast',()=>{const css=readFileSync(new URL('../src/next/ui/energyBox.css',import.meta.url),'utf8');assert.match(css,/\.hint-line:has\(\.box-inspection-toggle\)\{grid-template-columns:minmax\(0,1fr\) auto auto;grid-template-rows:minmax\(0,1fr\)/);assert.match(css,/height:22px;min-height:0;max-height:100%/);assert.match(css,/grid-template-rows:minmax\(0,1fr\) 22px/);});
test('every box type uses the same labeled rows; frozen and absolute zero differ in the same 解除 row (RULE-01)',async()=>{
 const {boxTypeRows}=await import('../src/next/ui/boxTypeInformation.ts');const state=createBattle({...base(),frozenRule:'half-melt-v1'});
 for(const type of boxTypeIds){const rows=boxTypeRows(b(0,type),state);assert.equal(rows[0]!.label,'効果');if(rows.length>1)assert.equal(rows[1]!.label,'解除');}
 const frozen=boxTypeRows(b(0,'frozen'),state),zero=boxTypeRows(b(0,'absolute-zero'),state);
 assert.match(frozen[1]!.text,/通常タイプへ戻ります/);assert.match(zero[1]!.text,/溶けず/);assert.equal(frozen[2]!.label,zero[2]!.label);
});
