import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,defaultConfig,createSkill,carryTransformationState} from '../src/next/core/index.ts';
import {revisedSkillTuning,defaultTuning,createTuning} from '../src/next/core/tuning.ts';
import {skillCatalog,skillDescription} from '../src/next/core/skillCatalog.ts';
import {resolveActiveDrop} from '../src/next/core/activeDrop.ts';
import {resolveInstantSkill} from '../src/next/core/instantSkills.ts';
import {sampleUniformIndex} from '../src/next/core/random.ts';
import {createNextStageConfig} from '../src/next/app/BattleRun.ts';
import {BattleController} from '../src/next/app/BattleController.ts';
import {playerPowerView} from '../src/next/ui/playerPower.ts';
import type {BattleState,Box,NormalSkillId} from '../src/next/core/types.ts';
const box=(row:number,col:number,type:Box['type']='normal',owner:Box['owner']='player'):Box=>({id:`b:${row}:${col}`,row,col,owner,type,status:'normal'});
const state=(id:NormalSkillId,rank:1|2=1)=>createBattle({...defaultConfig,tuning:revisedSkillTuning,characterId:'blue',initialBuild:{fixed:createSkill('health'),slots:[createSkill(id,rank),null],power:{3:0,4:0,5:0}},combatants:{...defaultConfig.combatants,enemy:{...defaultConfig.combatants.enemy,maxHp:999,initialHp:999}}});
const drop=(s:BattleState,row:number,col:number)=>resolveActiveDrop(s,{id:'fixture',available:true,landing:{row,col},spawn:{row,col},edge:{row,col,side:'top'},segmentEndRow:row,path:[{row,col}]});
function shape(id:NormalSkillId,rank:1|2=1){const cells=skillCatalog[id].pattern!.cells,origin=cells.at(-1)!;const s={...state(id,rank),boxes:cells.slice(0,-1).map(c=>box(c.row+3,c.col+1))};return {s,row:origin.row+3,col:origin.col+1};}
test('requested shape damage uses opponent maxHP, floors1%, and only upgraded shapes gain it',()=>{for(const [id,base,plus] of [['corner-strike',3,5],['square-strike',5,8],['cup-strike',8,15]] as const)for(const rank of [1,2] as const){const x=shape(id,rank);x.s.hp={...x.s.hp,enemy:{max:999,current:50}};const r=drop(x.s,x.row,x.col),e=r.events.find(e=>e.type==='damage'&&e.source===id);assert(e?.type==='damage');assert.equal(e.damage,rank===1?base:plus+9);}});
test('seeded X picks each link tier, boosts exactly1/2 once, deals no shape damage and keeps RNG deterministic',()=>{const seen=new Set<number>();for(const seed of [0,700,1400,2100])for(const rank of [1,2] as const){const x=shape('cross-strike',rank),s={...x.s,rngState:seed},draw=sampleUniformIndex(seed,3),tier=([3,4,5] as const)[draw.index]!,r=drop(s,x.row,x.col);seen.add(tier);assert.equal(r.state.build!.power[tier],rank);assert.equal(Object.values(r.state.build!.power).reduce((a,b)=>a+b),rank);assert.equal(r.state.rngState,draw.rngState);assert.equal(r.events.filter(e=>e.type==='power-boost').length,1);assert(!r.events.some(e=>e.type==='damage'&&e.source==='cross-strike'));assert.deepEqual(drop(s,x.row,x.col),r);}assert.equal(seen.size,3);});
test('X permanent power survives actual stage config/carry and checkpoint restore with HUD reflecting it',()=>{const x=shape('cross-strike',2),r=drop(x.s,x.row,x.col),next=carryTransformationState(createBattle(createNextStageConfig(x.s.config,{...r.state,hp:{...r.state.hp,enemy:{...r.state.hp.enemy,current:0}},result:{winner:'player',reason:'hp-zero'}},'marujiro',2)),r.state);assert.deepEqual(next.build!.power,r.state.build!.power);const c=new BattleController(next.config,{render(){},async animate(){}}),cp={...c.exportCheckpoint(),state:next};const restored=BattleController.restore(cp,{render(){},async animate(){}});assert.deepEqual(restored.snapshot.build!.power,r.state.build!.power);assert.deepEqual(playerPowerView(restored.snapshot),playerPowerView(next));});
test('last stand uses <=50% after insertion; base1.2/plus1.5 floor, not old flat bonus',()=>{for(const rank of [1,2] as const)for(const hp of [14,15,16]){const s=state('last-stand',rank),r=drop({...s,hp:{...s.hp,player:{max:30,current:hp}},boxes:[box(7,0),box(7,1)]},7,2),e=r.events.find(e=>e.type==='attack');assert(e?.type==='attack');assert.equal(e.damage,hp<=15?Math.floor(s.config.combatants.player.attacks[3]*(rank===1?1.2:1.5)):s.config.combatants.player.attacks[3]);}});
test('thorn loss enables last stand while shape healing before links can disable it',()=>{const s=state('last-stand',2);const thorn=drop({...s,config:{...s.config,thornRule:'owner-safe-v2'},hp:{...s.hp,player:{max:30,current:16}},boxes:[box(7,0),box(7,1),box(6,2,'thorn','enemy')]},7,2);assert(thorn.state.hp.player.current<=15);const e=thorn.events.find(e=>e.type==='attack');assert(e?.type==='attack');assert.equal(e.damage,Math.floor(s.config.combatants.player.attacks[3]*1.5));const healed=drop({...s,hp:{...s.hp,player:{max:30,current:15}},boxes:[box(5,2),box(6,1),box(6,2),box(6,3)]},7,2);assert(healed.state.hp.player.current>15);for(const e of healed.events)if(e.type==='attack')assert.equal(e.damage,s.config.combatants.player.attacks[e.tier]);});
test('capsule uses20/50% of maximum gauge, floors and caps, consumes one item; old tuning remains flat',()=>{for(const rank of [1,2] as const)for(const gauge of [0,119]){const s=state('capacitor',rank),r=resolveInstantSkill({...s,gauge},0);assert.equal(r.state.gauge,Math.min(120,gauge+(rank===1?24:60)));assert.equal(r.state.build!.slots[0],null);}const s=state('capacitor');const legacy={...s,config:{...s.config,tuning:defaultTuning}};assert.equal(resolveInstantSkill(legacy,0).state.gauge,12);assert.match(skillDescription('capacitor',2),/50%/);assert.match(skillDescription('last-stand',2),/1.5/);});

test('capsule percentages follow each frozen cap including300 and fractional results, never transformation cost',()=>{for(const cap of [120,150,300,121])for(const rank of [1,2] as const){const s=state('capacitor',rank),config={...s.config,tuning:createTuning({...revisedSkillTuning,gauge:{limits:{blue:{cost:80,cap}}}})};for(const gauge of [0,cap-1])assert.equal(resolveInstantSkill({...s,config,gauge},0).state.gauge,Math.min(cap,gauge+Math.floor(cap*(rank===1?20:50)/100)));}});
test('no X shape leaves RNG and permanent power untouched; legacy last stand keeps its additive rule',()=>{const x=state('cross-strike'),r=drop(x,7,0);assert.equal(r.state.rngState,x.rngState);assert.deepEqual(r.state.build!.power,x.build!.power);const s=state('last-stand'),legacy={...s,config:{...s.config,tuning:defaultTuning},hp:{...s.hp,player:{max:30,current:15}},boxes:[box(7,0),box(7,1)]};const e=drop(legacy,7,2).events.find(e=>e.type==='attack');assert(e?.type==='attack');assert.equal(e.damage,s.config.combatants.player.attacks[3]+3);});


test('X animation applies each boost once and never temporarily doubles HUD power',async()=>{
 const {createBattleAnimator}=await import('../src/next/ui/battleAnimator.ts');
 const x=shape('cross-strike',2),r=drop(x.s,x.row,x.col),snapshots:BattleState[]=[];
 const resolution={actor:'player' as const,originBoxId:r.originBoxId,enemyPlannedAction:null,events:r.events,links:r.links};
 await createBattleAnimator({motion:()=>({short:true,lowMotion:true}),playSound(){},describe(){},observe(){},highlight(){},render(s){snapshots.push(s);},drop(){},react(){},feedback(){return {remove(){}};},async transform(){},complete(){},async pause(){}})(resolution,x.s,r.state,new AbortController().signal);
 const totals=snapshots.map(s=>Object.values(s.build!.power).reduce((a,b)=>a+b,0));
 assert(totals.includes(0));assert(totals.includes(2));assert(totals.every(n=>n===0||n===2));
 assert.deepEqual(snapshots.at(-1)!.build!.power,r.state.build!.power);
 assert.equal(Object.values(x.s.build!.power).reduce((a,b)=>a+b,0),0);
});
