import {forecastAction,forecastPrimary} from '../src/next/ui/actionForecast.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {createProfile,freezeRunMeta,validateProfile,eligibleSkills} from '../src/next/meta/profile.ts';
import {prepareDeparture} from '../src/next/meta/departure.ts';
import {LEGACY_STARTERS} from '../src/next/meta/kits.ts';
import {createBattle,applyAction,createSkill,canReceiveSkillReward} from '../src/next/core/index.ts';
import {ownSquareCount,assignBoxType,poisonDamageSummary,resolvePoisonTurnEnd} from '../src/next/core/boxTypes.ts';
import {kitBoardTargets,canUseKitBoard} from '../src/next/core/kitBoards.ts';
import {BattleController} from '../src/next/app/BattleController.ts';
import {encodeSave,decodeSave} from '../src/next/app/saveCheckpoint.ts';
import type {RosterId} from '../src/next/meta/roster.ts';import type {BoardSkillId,Box,BattleState} from '../src/next/core/types.ts';
const box=(row:number,col:number,owner:Box['owner']='player',type:Box['type']='normal',poisonSource?:Box['poisonSource']):Box=>({id:`${row}:${col}`,row,col,owner,type,status:'normal',...(poisonSource?{poisonSource}:{})});
function config(id:RosterId,board?:BoardSkillId){const p=createProfile();p.ownedCharacters.push(...(['mint','amber','violet','silver','rose','imashiru'] as const));p.characters[id].xp=100;p.characters[id].tree.board=1;if(board)p.characters[id].board=board;const meta=freezeRunMeta(p,id,false);delete meta.characterRevision;return prepareDeparture(meta,1).config;}
test('legacy Violet starter and character-local diagonal pool remain valid with absent kitVersion',()=>{const p=createProfile();delete p.boardCatalogVersion;p.characters.violet.pool=['diagonal-shot','grow-fire','charge','first-guard','horizontal-slash','corner-strike'];p.characters.violet.board='pain-shared';validateProfile(p);assert(eligibleSkills(p,'violet').includes('diagonal-shot'));assert(!p.ownedSkills.includes('diagonal-shot'));const current=config('violet');const old={...current,meta:{...current.meta!,progressionVersion:undefined,boardCatalogVersion:undefined,boardBalance:undefined,kitVersion:undefined,kitBalance:undefined,board:'pain-shared' as const},initialBuild:{...current.initialBuild!,fixed:createSkill(LEGACY_STARTERS.violet)},initialGauge:100};const state=createBattle(old);assert.equal(applyAction(state,{type:'transform'}).state.transformation?.character,'red');const c=new BattleController(old,{render(){},async animate(){}},{run:{mode:'endless',rewards:true,route:'boss-loop',rewardMode:'categories',startStage:1,finishAtStage:50}});assert.equal(decodeSave(encodeSave(c.exportCheckpoint(),1)).checkpoint.state.build!.fixed.id,'diagonal-shot');});
test('legacy assassin fixed passive is non-upgradable, not a reward and not a pool no-op',()=>{const s=createBattle(config('violet'));assert.equal(s.build!.fixed.id,'poison-craft');assert.equal(canReceiveSkillReward(s.build!,'poison-craft'),false);assert(!s.config.meta!.pool.includes('poison-craft'));assert.equal(s.config.meta!.pool.length,6);});
test('current distinct own2x2 squares count overlaps and mixed owners correctly',()=>{const block=Array.from({length:9},(_,n)=>box(Math.floor(n/3),n%3));assert.equal(ownSquareCount(block,'player'),4);assert.equal(ownSquareCount(block.filter(b=>b.id!=='1:1'),'player'),0);assert.equal(ownSquareCount(block.filter(b=>b.id!=='0:0'),'player'),3);assert.equal(ownSquareCount(block.map(b=>b.id==='1:1'?{...b,owner:'enemy' as const}:b),'player'),0);assert.equal(ownSquareCount(block.map(b=>assignBoxType(b,'shiny')),'player'),4);});
test('Poisoning Art samples per-source current geometry, and gauge uses actualHP loss',()=>{const own=Array.from({length:6},(_,n)=>box(6+Math.floor(n/3),n%3));const s=createBattle({...config('violet'),initialBoxes:[...own,box(7,3,'enemy','poison','player'),box(7,4,'enemy','deadly-poison','player'),box(7,5,'enemy','poison'),box(6,5,'enemy','deadly-poison','enemy')]});assert.deepEqual(poisonDamageSummary(s,'enemy'),{boxes:4,base:6,bonus:4,squares:2,damage:10});const captured:BattleState={...s,boxes:s.boxes.map(b=>b.poisonSource==='player'?{...b,owner:'player'}:b),hp:{...s.hp,player:{...s.hp.player,current:1}}};const tick=resolvePoisonTurnEnd(captured,'player');assert.equal(tick.state.gauge,1);assert.equal(assignBoxType(s.boxes.find(b=>b.poisonSource==='player')!,'frozen').poisonSource,undefined);});
test('assassin board records its source; transform uses two deterministic enemy targets with no immediate damage',()=>{const s=createBattle({...config('violet'),initialGauge:150,initialBoxes:[box(7,0,'enemy'),box(7,1,'enemy'),box(7,2,'enemy')]});const poisoned=applyAction(s,{type:'board-skill',skillId:'violet-poison',target:{row:7,col:2}});assert(poisoned.accepted);assert.equal(poisoned.state.boxes.find(b=>b.col===2)!.poisonSource,'player');const transformed=applyAction(s,{type:'transform'});assert(transformed.accepted);assert.deepEqual(transformed.state.boxes.filter(b=>b.type==='deadly-poison').map(b=>b.col),[0,1]);assert.deepEqual(transformed.state.hp,s.hp);assert.equal(transformed.state.rngState,s.rngState);});
test('physical conversion keeps type and uses no passive attacks; Blue and Imashiru overwrite cleanly',()=>{for(const [id,skill,type] of [['amber','amber-convert','poison'],['red','red-capture','thorn']] as const){const s=createBattle({...config(id,skill),initialGauge:150,initialBoxes:[box(7,0,'enemy',type)]});const r=applyAction(s,{type:'board-skill',skillId:skill,target:{row:7,col:0}});assert(r.accepted);assert.equal(r.state.boxes[0]!.owner,'player');assert.equal(r.state.boxes[0]!.type,type);assert(!r.resolution!.events.some(e=>e.type==='attack'));}const s=createBattle({...config('imashiru','imashiru-focus'),initialGauge:60,initialBoxes:[box(7,0,'player','poison','player')]});const prepared={...s,shinyNextDrop:true};const r=applyAction(prepared,{type:'board-skill',skillId:'imashiru-focus',target:{row:7,col:0}});assert.equal(r.state.boxes[0]!.type,'shiny');assert.equal(r.state.boxes[0]!.poisonSource,undefined);assert(r.state.shinyNextDrop);});
test('technical L and horizontal masks remove only actual3-box patterns, never shape damage or link charge',()=>{for(const [id,skill,boxes] of [['mint','mint-observe',[box(6,0),box(7,0),box(7,1)]],['rose','rose-slice',[box(7,0),box(7,1),box(7,2)]]] as const){const s=createBattle({...config(id,skill),initialGauge:50,initialBoxes:boxes});const target={row:id==='mint'?6:7,col:0,orientation:0};assert.equal(kitBoardTargets(s,skill,target).length,3);const r=applyAction(s,{type:'board-skill',skillId:skill,target});assert(r.accepted);assert.equal(r.state.boxes.length,0);assert(!r.resolution!.events.some(e=>e.type==='attack'||e.type==='heal'||e.type==='damage'));assert(!canUseKitBoard(r.state,skill,target));}});
test('invalid targets spend no HP/gauge/turn; lethal Red cost does not capture the box',()=>{const s=createBattle({...config('red','red-capture'),combatants:{...config('red').combatants,player:{...config('red').combatants.player,initialHp:2}},initialBoxes:[box(7,0,'enemy')]});const invalid=applyAction(s,{type:'board-skill',skillId:'red-capture',target:{row:7,col:5}});assert(!invalid.accepted);assert.equal(invalid.state,s);const r=applyAction(s,{type:'board-skill',skillId:'red-capture',target:{row:7,col:0}});assert.equal(r.state.result!.winner,'enemy');assert.equal(r.state.boxes[0]!.owner,'enemy');});
test('legacy power starts6/9/13 and preserves its old current-turn link-gauge form',()=>{const base=config('amber'),s=createBattle({...base,meta:{...base.meta!,kitBalance:undefined},initialGauge:100,initialBoxes:[box(7,0),box(7,1)]});assert.deepEqual(s.config.combatants.player.attacks,{3:6,4:9,5:13});const t=applyAction(s,{type:'transform'}).state,r=applyAction(t,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.resolution!.events.find(e=>e.type==='attack')!.damage,6);const g=r.resolution!.events.find(e=>e.type==='gauge'&&e.source==='link')!;assert.equal(g.type==='gauge'&&g.amount,4);assert.equal(r.state.transformation,null);});
test('guardian barrier absorbs enemy attack after FirstGuard but bypasses poison and selfcost',()=>{const s=createBattle({...config('silver'),initialGauge:100,initialBoxes:[box(7,0,'enemy'),box(7,2,'enemy')],combatants:{...config('silver').combatants,enemy:{...config('silver').combatants.enemy,attacks:{3:6,4:6,5:6}}}});const transformed=applyAction(s,{type:'transform'}).state;assert.equal(transformed.barrier,12);const enemy={...transformed,barrier:3,actor:'enemy' as const};const r=applyAction(enemy,{type:'enemy'});assert(r.accepted);assert((r.state.barrier??0)<=3);const poison={...transformed,boxes:[box(7,0,'player','deadly-poison')]};const poisoned=resolvePoisonTurnEnd(poison,'player');assert.equal(poisoned.state.hp.player.current,poison.hp.player.current-2);assert.equal(poisoned.state.barrier,12);});

test('targeted and reserved shine forecasts expose exact gauge debit before end-turn recharge',()=>{for(const skill of ['imashiru-focus','imashiru-insight'] as const){const s=createBattle({...config('imashiru',skill),initialGauge:230,initialBoxes:[box(7,0)]});const v=forecastAction(s,{type:'board-skill',skillId:skill,...(skill==='imashiru-focus'?{target:{row:7,col:0}}:{})})!;assert.equal(v.gaugeSpent,skill==='imashiru-focus'?40:30);assert.match(forecastPrimary(v),new RegExp(`ゲージ −${v.gaugeSpent}`));}});
