import {normalSkillIds,skillCatalog} from '../src/next/core/skillCatalog.ts';
import {LEGACY_BOARDS} from '../src/next/meta/kits.ts';
import {reconcileSavedProgress} from '../src/next/meta/reconciliation.ts';
import {LocalSave} from '../src/next/app/localSave.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {createProfile,ProfileStore,levelInfo,validateProfile,validatePool,freezeRunMeta,settleProfile,resultReceipt,drawGacha,eligibleSkills} from '../src/next/meta/profile.ts';
import {roster,rosterIds} from '../src/next/meta/roster.ts';
import {prepareDeparture} from '../src/next/meta/departure.ts';
import {BattleController} from '../src/next/app/BattleController.ts';
import {validateCheckpoint,encodeSave,decodeSave} from '../src/next/app/saveCheckpoint.ts';
import type {RunCheckpoint} from '../src/next/app/saveCheckpoint.ts';
import {createBattle,applyAction,getAvailableBoardSkills} from '../src/next/core/index.ts';
import {createSkill,acquireSkill,useBuildSlot,validatePlayerBuild} from '../src/next/core/playerBuild.ts';
import {generateCategoryOffer} from '../src/next/app/rewards.ts';
import {rewardSlotToken,planRewardInteraction} from '../src/next/ui/rewardInteraction.ts';
import {consumableUseView} from '../src/next/ui/consumableReadability.ts';
import {prepareTrialSetup} from '../src/next/config.ts';
type Mutable<T>={-readonly [K in keyof T]:T[K]};
const view={render(){},async animate(){}};
class Storage {data=new Map<string,string>();fail=false;uncertain=false;readFail=false;getItem(k:string){if(this.readFail)throw new Error('read');return this.data.get(k)??null;}setItem(k:string,v:string){if(this.fail)throw new Error('quota');this.data.set(k,v);if(this.uncertain){this.uncertain=false;throw new Error('after-write');}}}
function started(id:'blue'|'red'='blue'){const p=createProfile(123);p.selected=id;const setup=prepareDeparture(freezeRunMeta(p,id,true),7),c=new BattleController(setup.config,view,setup.options),cp=c.exportCheckpoint();p.launches[cp.runId]={character:id,snapshot:JSON.stringify(cp.initialConfig.meta)};return {p,cp};}
function terminal(clear=false){const {p,cp}=started();const c=structuredClone(cp) as Mutable<RunCheckpoint>;c.run={...c.run!,stage:clear?50:4,defeatedCount:clear?50:3,status:clear?'cleared':'lost'};c.state={...c.state,hp:{...c.state.hp,player:{...c.state.hp.player,current:clear?10:0},enemy:{...c.state.hp.enemy,current:clear?0:30}},result:{winner:clear?'player':'enemy',reason:'hp-zero'}};return {p,cp:c};}
test('new profile owns two characters, six shared skills, separate valid pools for all eight',()=>{const p=createProfile(1);validateProfile(p);assert.deepEqual(p.ownedCharacters,['blue','red']);assert.equal(p.coins,0);assert.equal(p.energy,0);assert.equal(rosterIds.length,8);for(const id of rosterIds){assert.equal(p.characters[id].pool.length,6);assert.equal(new Set(p.characters[id].pool).size,6);assert.equal(p.characters[id].pool.includes('health'),id==='blue');} });
test('level thresholds and earned tree points are character-specific and deterministic',()=>{assert.deepEqual(levelInfo(0),{level:1,current:0,next:40,points:2});assert.equal(levelInfo(39).level,1);assert.equal(levelInfo(40).level,2);assert.equal(levelInfo(100).level,3);assert.equal(levelInfo(1e7).level,12);const p=createProfile();p.characters.blue.xp=100;assert.equal(levelInfo(p.characters.red.xp).level,1);});
test('tree overspend, invalid ranks, locked boards and invalid inventory fail closed',()=>{const base=createProfile();for(const edit of [(p:typeof base)=>p.characters.blue.tree.slots=1,(p:typeof base)=>p.characters.blue.tree.three=6,(p:typeof base)=>p.characters.blue.board='ember',(p:typeof base)=>p.ownedSkills.push('health')]){const p=structuredClone(base);edit(p);assert.throws(()=>validateProfile(p));}});
test('six-minimum, twenty maximum, duplicates, ownership and intrinsic restrictions are validated',()=>{const p=createProfile();assert.throws(()=>validatePool(p,'red',['health',...p.characters.red.pool.slice(1)]));assert.throws(()=>validatePool(p,'blue',p.characters.blue.pool.slice(1)));assert.throws(()=>validatePool(p,'blue',[...p.characters.blue.pool,'health']));assert.throws(()=>validatePool(p,'blue',[...p.characters.blue.pool,'magic-bullet']));p.ownedSkills.push('magic-bullet');validatePool(p,'blue',[...p.characters.blue.pool,'magic-bullet']);});
test('all eight registry entries launch with their actual starter, stats, board and stable resume identity',()=>{const p=createProfile();p.ownedCharacters=[...rosterIds];for(const id of rosterIds){const meta=freezeRunMeta(p,id,true),setup=prepareDeparture(meta,1),c=new BattleController(setup.config,view,setup.options),state=c.snapshot;assert.equal(state.build!.fixed.id,roster[id].starter);assert.equal(state.config.meta!.rosterId,id);assert.equal(state.hp.player.max,roster[id].hp);assert.deepEqual(getAvailableBoardSkills(state),id==='blue'||id==='red'?[roster[id].board]:[]);const restored=BattleController.restore(decodeSave(encodeSave(c.exportCheckpoint(),1)).checkpoint,view);assert.deepEqual(JSON.parse(JSON.stringify(restored.snapshot)),JSON.parse(JSON.stringify(state)));assert.equal(eligibleSkills(p,id).includes('health'),id==='blue');}});
test('departure freezes tree, level, pool and board against all later profile changes',()=>{const p=createProfile();p.characters.blue.xp=100;p.characters.blue.tree={three:1,four:1,five:1,slots:0,board:1};p.characters.blue.board='blue-plumb';const m=freezeRunMeta(p,'blue',true),setup=prepareDeparture(m,1),before=JSON.stringify(setup);p.characters.blue.tree.three=0;p.characters.blue.pool.reverse();p.characters.blue.board='pain-shared';assert.equal(JSON.stringify(setup),before);assert.deepEqual(setup.config.combatants.player.attacks,{3:5,4:8,5:13});assert.equal(setup.config.meta!.board,'blue-plumb');assert.deepEqual(getAvailableBoardSkills(createBattle(setup.config)),[]);});
test('additional slots equip, replace, consume, serialize, and validate all four positions',()=>{const p=createProfile();p.characters.red.xp=100;p.characters.red.tree.slots=2;const setup=prepareDeparture(freezeRunMeta(p,'red',true),1);let b=createBattle(setup.config).build!;for(const id of ['charge','first-guard','square-strike','magic-bullet'] as const)b=acquireSkill(b,id)!;assert.equal(b.slots.length,4);assert.equal(b.slots[3]!.id,'magic-bullet');validatePlayerBuild(b,setup.config);assert.equal(rewardSlotToken(b,3),'magic-bullet:1:1');assert.equal(consumableUseView(b.slots[3],3,b.slots.length)!.slot,3);assert.equal(useBuildSlot(b,3)!.slots[3],null);assert.equal(acquireSkill(b,'corner-strike',3)!.slots[3]!.id,'corner-strike');assert.equal(acquireSkill(b,'corner-strike',4),null);assert.equal(useBuildSlot(b,4),null);const state=createBattle({...setup.config,initialBuild:b});assert(applyAction(state,{type:'instant-skill',slot:3}).accepted);});
test('expanded replacement UI accepts real index3 and rejects out-of-range stale identities',()=>{const p=createProfile();p.characters.red.xp=100;p.characters.red.tree.slots=2;const setup=prepareDeparture(freezeRunMeta(p,'red',false),1),s=createBattle({...setup.config,initialBuild:{fixed:createSkill('grow-fire'),slots:[createSkill('charge'),createSkill('first-guard'),createSkill('square-strike'),createSkill('magic-bullet')],power:{3:0,4:0,5:0}}});const offer={id:'a',category:'skills' as const,choices:['corner-strike' as const]},ui={selected:'corner-strike' as const,replacing:true,replacementSlot:null};assert(planRewardInteraction(s,offer,ui,{type:'slot',value:'3',offerId:'a',category:'skills',slotToken:rewardSlotToken(s.build!,3)!}));assert.equal(planRewardInteraction(s,offer,ui,{type:'slot',value:'4',offerId:'a',category:'skills'}),null);});
test('frozen reward pool restricts categories, commits empty/exhausted pool without RNG or duplicates',()=>{const {cp}=started('red');const pool=cp.initialConfig.meta!.pool;for(let seed=0;seed<30;seed++){const result=generateCategoryOffer(cp.state.build!,seed,'x','skills',undefined,pool);assert(result.offer.choices.every(id=>pool.includes(id as never)));assert.equal(new Set(result.offer.choices).size,result.offer.choices.length);}const empty=generateCategoryOffer(cp.state.build!,23,'x','skills',undefined,[]);assert.deepEqual(empty.offer.choices,[]);assert.equal(empty.rngState,23);});
test('Health cannot be equipped, awarded or injected into any non-owner starter',()=>{const p=createProfile();p.ownedCharacters=[...rosterIds];for(const id of rosterIds.filter(x=>x!=='blue')){const setup=prepareDeparture(freezeRunMeta(p,id,false),2);const state=createBattle(setup.config);assert.equal(acquireSkill(state.build!,'health'),null);assert.throws(()=>createBattle({...setup.config,initialBuild:{...state.build!,slots:[createSkill('health'),null]}}));}});
test('defeat pays only recorded kills; clear50 grants extra reward and first/per-character trophies once',()=>{for(const clear of [false,true]){const {p,cp}=terminal(clear);validateCheckpoint(cp);const next=settleProfile(p,cp,77);assert.equal(next.coins,clear?450:15);assert.equal(next.characters.blue.xp,clear?750:30);assert.equal(next.characters.red.xp,0);assert.equal(Object.keys(next.trophies).length,clear?2:0);assert.deepEqual(settleProfile(next,cp,99),next);assert.equal(Object.keys(next.receipts).length,1);}});
test('second clear on a different character retains first-clear timestamp and adds one character trophy',()=>{const {p,cp}=terminal(true),a=settleProfile(p,cp,1);const other=structuredClone(cp) as Mutable<RunCheckpoint>;other.runId=crypto.randomUUID();other.initialConfig={...other.initialConfig,meta:{...other.initialConfig.meta!,rosterId:'red'}};other.state={...other.state,config:other.initialConfig};a.launches[other.runId]={character:'red',snapshot:JSON.stringify(other.initialConfig.meta)};const b=settleProfile(a,other,2);assert.equal(b.trophies['clear50:first'],1);assert.equal(b.trophies['clear50:red'],2);assert.equal(b.receipts[other.runId]!.trophies.length,1);});
test('QA, old saves, active runs, unregistered runs and changed departure snapshots never earn',()=>{const original=terminal(true);for(const kind of ['qa','old','active','unregistered','changed'] as const){const p=structuredClone(original.p),cp=structuredClone(original.cp) as Mutable<RunCheckpoint>;if(kind==='qa')cp.initialConfig={...cp.initialConfig,meta:{...cp.initialConfig.meta!,eligible:false}};if(kind==='old'){cp.initialConfig={...cp.initialConfig,meta:undefined};}if(kind==='active')cp.run={...cp.run!,status:'active'};if(kind==='unregistered')p.launches={};if(kind==='changed')cp.initialConfig={...cp.initialConfig,meta:{...cp.initialConfig.meta!,level:2}};assert.equal(resultReceipt(p,cp),null);assert.equal(settleProfile(p,cp),p);}});
test('legacy saves still round-trip without modification and retain old unrestricted reward behavior',()=>{const setup=prepareTrialSetup({character:'blue',firstEnemy:'marujiro',seed:1,mode:'manual',stage:1,fixture:'normal',route:'boss-loop'}),cp=new BattleController(setup.config,view,setup.options).exportCheckpoint();assert.equal(cp.initialConfig.meta,undefined);assert.deepEqual(decodeSave(encodeSave(cp,1)).checkpoint,JSON.parse(JSON.stringify(cp)));assert.equal(resultReceipt(createProfile(),cp),null);});
test('profile and run use distinct storage, QA is isolated, and ownership is mandatory',()=>{const s=new Storage();let owns=true;const a=new ProfileStore(s,()=>owns),q=new ProfileStore(s,()=>owns,'/energy-qa/');a.read();q.read();assert.notEqual(a.key,q.key);a.update(p=>{p.coins=99;return p;});assert.equal(q.current.coins,0);owns=false;assert.throws(()=>a.guard());assert.throws(()=>a.update(p=>p));});
test('terminal checkpoint before profile failure recovers once, including after-write uncertainty',()=>{for(const uncertain of [false,true]){const {p,cp}=terminal(true),s=new Storage(),a=new ProfileStore(s,()=>true);a.read();a.write(p);s.fail=!uncertain;s.uncertain=uncertain;assert.throws(()=>a.settle(cp));s.fail=false;a.guard();a.settle(cp);assert.equal(a.current.coins,450);a.settle(cp);assert.equal(a.current.coins,450);const reload=new ProfileStore(s,()=>true);reload.read();reload.settle(cp);assert.equal(reload.current.characters.blue.xp,750);}});
test('external profile overwrite stops actions without modifying unrelated or corrupt bytes',()=>{const s=new Storage(),a=new ProfileStore(s,()=>true);a.read();s.data.set(a.key,'external');assert.throws(()=>a.update(p=>drawGacha(p)));assert.equal(s.data.get(a.key),'external');assert.throws(()=>new ProfileStore(s,()=>true).read());assert.equal(s.data.get(a.key),'external');});
test('gacha deducts once with persisted result, deterministic RNG, and no reload reroll',()=>{const s=new Storage(),a=new ProfileStore(s,()=>true);a.read();a.update(p=>{p.coins=1000;p.rng=42;return p;});const before=a.current,expected=drawGacha(before);a.update(drawGacha);assert.deepEqual(a.current.lastDraw,expected.lastDraw);assert.equal(a.current.coins,expected.coins);const b=new ProfileStore(s,()=>true);b.read();assert.deepEqual(b.current,a.current);assert.equal(b.current.drawCount,1);});
test('gacha never touches combat RNG, never grants intrinsic Health, and all categories/dupes are reachable',()=>{let p=createProfile(19);p.coins=100000;const categories=new Set(),duplicates=new Set();for(let i=0;i<500;i++){p.pendingDraw=false;p=drawGacha(p);categories.add(p.lastDraw!.kind);if(p.lastDraw!.duplicate)duplicates.add(p.lastDraw!.kind);assert.notEqual(p.lastDraw!.item,'health');}assert.deepEqual([...categories].sort(),['character','energy','skill']);assert.deepEqual([...duplicates].sort(),['character','skill']);assert.equal(p.ownedCharacters.length,8);assert.equal(new Set(p.ownedSkills).size,normalSkillIds.filter(id=>!['starter-upgrade-only','never','trophy'].includes(skillCatalog[id].rewardAccess??'shared')).length);validateProfile(p);});
test('insufficient currency fails without RNG, currency or last-result changes',()=>{const p=createProfile(5),raw=JSON.stringify(p);assert.throws(()=>drawGacha(p));assert.equal(JSON.stringify(p),raw);});
test('snapshot mismatch, overspent tree, intrinsic pool and capacity mismatch cannot restore',()=>{const {cp}=started();for(const change of [(c:RunCheckpoint)=>{c.initialConfig.meta!.tree.three=5;},(c:RunCheckpoint)=>{c.initialConfig.meta!.slots=4;},(c:RunCheckpoint)=>{(c as Mutable<RunCheckpoint>).state={...c.state,config:{...c.state.config,meta:{...c.state.config.meta!,pool:[...c.state.config.meta!.pool,'magic-bullet']}}};}]){const c=structuredClone(cp);change(c);assert.throws(()=>validateCheckpoint(c));}});

test('unacknowledged gacha result blocks duplicate taps and persists across reload',()=>{const s=new Storage(),a=new ProfileStore(s,()=>true);a.read();a.update(p=>{p.coins=500;return p;});a.update(drawGacha);const raw=JSON.stringify(a.current);assert.throws(()=>a.update(drawGacha));assert.equal(JSON.stringify(a.current),raw);const reload=new ProfileStore(s,()=>true);reload.read();assert.throws(()=>reload.update(drawGacha));reload.update(p=>{p.pendingDraw=false;return p;});reload.update(drawGacha);assert.equal(reload.current.drawCount,2);});

test('array-shaped profile maps cannot silently drop string-keyed receipts or launches',()=>{for(const key of ['receipts','launches','trophies','characters']){const p=createProfile();(p as unknown as Record<string,unknown>)[key]=[];assert.throws(()=>validateProfile(p));}const p=createProfile();(p.characters.blue as unknown as Record<string,unknown>).tree=[];assert.throws(()=>validateProfile(p));});

test('failed terminal settlement blocks replacement; recovery pays once before the new checkpoint replaces it',()=>{const {p,cp}=terminal(true),s=new Storage(),profile=new ProfileStore(s,()=>true),save=new LocalSave(s,()=>true);profile.read();profile.write(p);save.read();save.write(cp);const previous=JSON.stringify(save.latest);let replacements=0;const replace=()=>{reconcileSavedProgress(save,profile);replacements++;const setup=prepareDeparture(freezeRunMeta(profile.current,'blue',true),22);save.write(new BattleController(setup.config,view,setup.options).exportCheckpoint());};s.fail=true;assert.throws(replace);assert.equal(replacements,0);assert.equal(JSON.stringify(save.latest),previous);s.fail=false;replace();assert.equal(replacements,1);assert.equal(profile.current.coins,450);assert.equal(profile.current.characters.blue.xp,750);assert.notEqual(save.latest!.checkpoint.runId,cp.runId);profile.settle(cp);assert.equal(profile.current.coins,450);});


test('first gacha acquisition upgrades only a locked legacy default; owned choices and other progress stay intact',()=>{
 const seeds={mint:1972,amber:1973,violet:1975,silver:1976,rose:1978,imashiru:1980} as const;
 for(const [id,seed] of Object.entries(seeds) as [keyof typeof seeds,number][]){
  const p=createProfile(seed);delete p.boardCatalogVersion;p.coins=100;p.characters[id].board=LEGACY_BOARDS[id];const progress=structuredClone(p.characters[id]);const raw=JSON.stringify(p);
  const gained=drawGacha(p);assert.equal(gained.lastDraw!.item,id);assert.equal(gained.lastDraw!.duplicate,false);assert.equal(gained.characters[id].board,roster[id].board);assert.deepEqual({...gained.characters[id],board:progress.board},progress);assert.equal(JSON.stringify(p),raw);validateProfile(gained);
  assert.equal(prepareDeparture(freezeRunMeta(gained,id,true),1).config.meta!.board,roster[id].board);
  const owned=structuredClone(p);owned.ownedCharacters=[...rosterIds];const duplicate=drawGacha(owned);assert.equal(duplicate.lastDraw!.duplicate,true);assert.equal(duplicate.characters[id].board,LEGACY_BOARDS[id]);assert.deepEqual(duplicate.characters[id],owned.characters[id]);
 }
 const custom=createProfile(1972);delete custom.boardCatalogVersion;custom.coins=100;custom.characters.mint.xp=100;custom.characters.mint.tree.board=1;custom.characters.mint.board='ember';const gained=drawGacha(custom);assert.equal(gained.characters.mint.board,'ember');assert.deepEqual(gained.characters.mint,custom.characters.mint);
});
