import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {registerHooks} from 'node:module';import ts from 'typescript';
import {ProfileStore,resultReceipt} from '../src/next/meta/profile.ts';import {BattleController} from '../src/next/app/BattleController.ts';import {LocalSave,SAVE_KEY} from '../src/next/app/localSave.ts';import {canRetireCheckpoint,prepareRetiredCheckpoint} from '../src/next/app/saveCheckpoint.ts';import {roster} from '../src/next/meta/roster.ts';
class Element{id='';hidden=false;open=false;innerHTML='';scrollTop=0;listeners:Record<string,Function[]>={};children:Element[]=[];dataset:Record<string,string>={};disabled=false;attrs=new Set<string>();style={setProperty(){}};classList={add(){},remove(){}};setAttribute(){}append(...e:Element[]){this.children.push(...e);}querySelector(){return null;}querySelectorAll(){return [];}addEventListener(n:string,f:Function){(this.listeners[n]??=[]).push(f);}contains(){return false;}showModal(){this.open=true;}close(){this.open=false;for(const f of this.listeners.close??[])f({});}closest(){return this;}hasAttribute(n:string){return this.attrs.has(n);}}
test('actual home cancellation, terminal Continue and reward-boundary gates match the return controller',async()=>{
const g=globalThis as any;g.HTMLElement=Element;g.HTMLButtonElement=Element;g.document={activeElement:null,createElement:()=>new Element(),body:{classList:{add(){},remove(){}}}};const hook=registerHooks({load(url,c,next){return url.endsWith('.css')?{format:'module',source:'export {};',shortCircuit:true}:next(url,c);}});const {mountHome}=await import('../src/next/meta/home.ts');
const main=readFileSync(new URL('../src/next/main.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('main.ts',main,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='requestRetirement')!;const code=ts.transpileModule('let selected=null;'+node.getText(ast)+';return requestRetirement;',{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
const fixtures=JSON.parse(readFileSync(new URL('./fixtures/natural-return-replays.json',import.meta.url),'utf8'));let checks=0;
for(const key of ['defeated-0-active','defeated-10-active','defeated-49-active','reward-pending','reward-committed']){const f=fixtures.find((x:any)=>x.tag==='new'&&x.character==='blue'),cp=f.entries.find((x:any)=>x.key===key).checkpoint;let owned=true,accept=false,continueCalls=0;const storage={data:new Map<string,string>(),getItem(k:string){return this.data.get(k)??null;},setItem(k:string,v:string){this.data.set(k,v);}};g.localStorage=storage;const profileStore=new ProfileStore(storage,()=>owned);profileStore.read();profileStore.write(f.profile);profileStore.update(p=>{p.selected='red';return p;});const save=new LocalSave(storage,()=>owned);save.read();save.write(cp);const controller=BattleController.restore(cp,{render(){},async animate(){throw Error('Return must not animate combat');}},{beforeAction(){save.guard();profileStore.guard();},write(c){save.write(c);profileStore.settle(c);},failed(e){throw e;}});const root=new Element();let request:()=>boolean;const home=mountHome(root as any,{store:()=>profileStore,saved:()=>save.latest?.checkpoint??null,continue(){continueCalls++;},retire:()=>request(),async launch(){throw Error('No automatic new run');},preview:false});const window={confirm:()=>accept};g.window=window;const injected={save,profileStore,controller,canRetireCheckpoint,prepareRetiredCheckpoint,resultReceipt,roster,window,home,details:{close(){}},rewardDialog:{reset(){}},saveDialog:{close(){}}};request=new Function(...Object.keys(injected),code)(...Object.values(injected));home.show();const [surface,panel]=root.children as [Element,Element];assert(surface.innerHTML.includes('data-home="continue"'));assert(!surface.innerHTML.includes('data-home="launch"'));const btn=new Element();btn.dataset.home='return';const rawRun=storage.getItem(SAVE_KEY),rawProfile=storage.getItem(profileStore.key);if(key.startsWith('reward')){assert.match(surface.innerHTML,/data-home="return"[^>]*disabled/);assert.throws(()=>request());assert.equal(storage.getItem(SAVE_KEY),rawRun);checks++;continue;}
 surface.listeners.click![0]!({target:btn});assert(home.active);assert.equal(storage.getItem(SAVE_KEY),rawRun);assert.equal(storage.getItem(profileStore.key),rawProfile);assert.equal(continueCalls,0);accept=true;surface.listeners.click![0]!({target:btn});assert(!home.active);assert.equal(save.latest!.checkpoint.run!.status,'retired');home.show();assert(!surface.innerHTML.includes('data-home="continue"'));assert(surface.innerHTML.includes('data-home="launch"'));assert.equal(profileStore.current.characters.red.xp,f.profile.characters.red.xp);assert.equal(profileStore.current.characters.blue.xp,f.profile.characters.blue.xp+cp.run.defeatedCount*10);
 // Read-only inspection of the actual backup panel gate after return; no restore/import action is submitted.
 const records=new Element();records.dataset.home='records';surface.listeners.click![0]!({target:records});const backup=new Element();backup.dataset.subpage='backup';panel.listeners.click![0]!({target:backup});assert(panel.innerHTML.includes('成長データをファイルに保存'));checks++;}
hook.deregister();assert.equal(checks,5);
});
