import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {SPEED_MUSIC,MOTHER_MUSIC} from '../src/next/audio/bossMusic.ts';
const contracts=JSON.parse(readFileSync(new URL('../docs/boss-music-v1/asset-contracts.json',import.meta.url),'utf8'));
for(const [index,asset] of [SPEED_MUSIC,MOTHER_MUSIC].entries())test(`boss audio ${index+1} keeps reviewed hashes, exact FLAC frames and matching PCM fallback`,()=>{
 const c=contracts[index];for(const filename of [c.runtimeFile,c.fallbackFile]){const bytes=readFileSync(new URL(`../public/assets/audio/boss-v1/${filename}`,import.meta.url)),contract=c.files.find((file:{filename:string})=>file.filename===filename);assert.equal(bytes.length,contract.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),contract.sha256);}
 const flac=readFileSync(new URL(`../public${asset.url}`,import.meta.url));assert.equal(flac.toString('ascii',0,4),'fLaC');assert.equal(flac[4]!&127,0);assert.equal(flac.readUIntBE(5,3),34);const stream=flac.readBigUInt64BE(18);assert.equal(Number(stream>>44n),c.sampleRate);assert.equal(Number((stream>>41n)&7n)+1,c.channels);assert.equal(Number((stream>>36n)&31n)+1,16);assert.equal(Number(stream&((1n<<36n)-1n)),c.frames);
 const wav=readFileSync(new URL(`../public${asset.fallbackUrl}`,import.meta.url));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.toString('ascii',8,12),'WAVE');let channels=0,rate=0,bits=0,dataBytes=0;for(let offset=12;offset+8<=wav.length;){const name=wav.toString('ascii',offset,offset+4),length=wav.readUInt32LE(offset+4);assert(offset+8+length<=wav.length);if(name==='fmt '){assert.equal(wav.readUInt16LE(offset+8),1);channels=wav.readUInt16LE(offset+10);rate=wav.readUInt32LE(offset+12);bits=wav.readUInt16LE(offset+22);}if(name==='data')dataBytes=length;offset+=8+length+(length%2);}
 assert.equal(channels,2);assert.equal(rate,c.sampleRate);assert.equal(bits,16);assert.equal(dataBytes/(channels*bits/8),c.frames);assert.equal(asset.loopEndSeconds,c.frames/c.sampleRate);assert.equal(asset.loopStartSeconds,0);assert.equal(asset.loopWholeBuffer,true);
});
