import test from 'node:test';
import assert from 'node:assert/strict';
import { applyAction, createBattle, createPlayerBuild, createSkill, createTuning, getEnemyIntent, getEnemyDefinition } from '../src/next/core/index.ts';
import { createTrialConfig, prepareTrialSetup } from '../src/next/config.ts';
import { bossLoopEncounter, endlessEncounter } from '../src/next/app/progression.ts';
import { BattleController } from '../src/next/app/BattleController.ts';
import type { BattleConfig, BattleState, Box, EnemyId, EnemyIntent, Resolution } from '../src/next/core/types.ts';
const box=(row:number,col=0,owner:Box['owner']='enemy'):Box=>({id:`b${row}:${col}`,row,col,owner,type:'normal',status:'normal'});
function config(enemy:EnemyId='mother-core',count=0):BattleConfig{return {...createTrialConfig('blue',enemy),firstActor:'enemy',initialEnemyTurnCount:count};}
const stepTypes=(intent:EnemyIntent)=>intent.type==='sequence'?intent.steps.map(x=>x.type):[intent.type];
const enemy=(s:BattleState)=>applyAction(s,{type:'enemy'});
const activeEnemy=(s:BattleState)=>({...s,actor:'enemy' as const});
function controller(config:BattleConfig,stage:number){const resolutions:Resolution[]=[];const c=new BattleController(config,{render(){},async animate(r){resolutions.push(r);}},{run:{mode:'endless',rewards:true,rewardMode:'categories',route:'boss-loop',startStage:stage}});return {c,resolutions};}

test('boss bases are separate from first-loop encounter growth',()=>{assert.deepEqual(getEnemyDefinition('speed-core').attacks,{3:6,4:7,5:9});assert.equal(getEnemyDefinition('speed-core').maxHp,50);assert.deepEqual(getEnemyDefinition('mother-core').attacks,{3:5,4:8,5:12});assert.equal(getEnemyDefinition('mother-core').maxHp,150);assert.deepEqual([25,40,50].map(s=>bossLoopEncounter(s).maxHp),[290,440,640]);});
test('local stage repeats exactly and HP/link/fixed growth each apply once per loop',()=>{for(let stage=1;stage<=150;stage++){const r=bossLoopEncounter(stage),base=bossLoopEncounter(r.localStage);assert.equal(r.enemyId,base.enemyId);assert.equal(r.maxHp,base.maxHp*(1+2*r.loopIndex));assert.deepEqual(r.attacks,{3:base.attacks[3]+2*r.loopIndex,4:base.attacks[4]+2*r.loopIndex,5:base.attacks[5]+2*r.loopIndex});assert.equal(r.fixedDamageBonus,r.loopIndex);}assert.equal(bossLoopEncounter(51).maxHp,180);assert.equal(bossLoopEncounter(75).maxHp,870);assert.equal(bossLoopEncounter(90).maxHp,1320);assert.equal(bossLoopEncounter(100).maxHp,1920);assert.equal(bossLoopEncounter(101).maxHp,300);assert.equal(bossLoopEncounter(125).maxHp,1450);});
test('boss scheduling, old route, tuning and range validation remain independent',()=>{assert.deepEqual([24,25,26,39,40,41,49,50,51,75,90,100].map(s=>bossLoopEncounter(s).enemyId),['nigirin','speed-core','hikikizan','nigirin','speed-core','hikikizan','marujiro','mother-core','marujiro','speed-core','speed-core','mother-core']);assert.equal(endlessEncounter(25).enemyId,'marujiro');const t=createTuning({progression:{hpMultiplierStep:1,attackPerLoop:3,fixedDamagePerLoop:2}});assert.equal(bossLoopEncounter(75,'marujiro',t).maxHp,580);assert.equal(bossLoopEncounter(75,'marujiro',t).attacks[3],9);assert.equal(bossLoopEncounter(75,'marujiro',t).fixedDamageBonus,2);for(const s of [0,-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER])assert.throws(()=>bossLoopEncounter(s));});
test('Speed Core owns a five-turn clock, damage precedes its insertion and does not replace it',()=>{const base=config('speed-core');let s=createBattle({...base,combatants:{...base.combatants,player:{maxHp:10000,initialHp:10000,attacks:{3:4,4:7,5:11}}}});for(let turn=1;turn<=10;turn++){const r=enemy(activeEnemy(s));assert.ok(r.accepted);const types=r.resolution!.events.map(e=>e.type);assert.equal(types.filter(t=>t==='drop').length,1);const fixed=r.resolution!.events.find(e=>e.type==='damage');assert.equal(!!fixed,turn%5===0);if(fixed){assert.equal(fixed.type==='damage'&&fixed.damage,3);assert.ok(types.indexOf('damage')<types.indexOf('drop'));}assert.equal(r.state.enemyTurnCount,turn);assert.equal(r.state.actor,'player');s=r.state;assert.equal(s.result,null);}});
test('fixed damage KO stops before RNG, drop, blocked fallback or further input',()=>{const base=config('speed-core',4);const s=createBattle({...base,combatants:{...base.combatants,player:{...base.combatants.player,initialHp:2}},board:{width:1,height:1,gravity:'down',terrain:[],invalidCells:[]},initialBoxes:[box(0)]});const r=enemy(s);assert.equal(r.state.result?.reason,'hp-zero');assert.equal(r.state.rngState,s.rngState);assert.equal(r.state.gauge,2);assert.deepEqual(r.resolution!.events.map(e=>e.type),['damage','gauge','battle-end']);assert.equal(enemy(r.state).accepted,false);});
test('fixed attacks bypass first-link guard and charge only actual HP loss',()=>{const b=config('speed-core',4);const build={...createPlayerBuild('blue'),slots:[createSkill('first-guard'),null] as const};const r=enemy(createBattle({...b,initialBuild:build}));assert.equal(r.state.hp.player.current,27);assert.equal(r.state.gauge,3);});
test('Mother Core normal sequence counts enemy turns rather than two-drop insertions',()=>{let s=createBattle({...config(),board:{width:6,height:30,gravity:'down',terrain:[],invalidCells:[]},combatants:{...config().combatants,player:{maxHp:10000,initialHp:10000,attacks:{3:4,4:7,5:11}}}});const counts=[];for(let i=0;i<14;i++){const r=enemy(activeEnemy(s));counts.push(r.resolution!.events.filter(e=>e.type==='drop').length);assert.equal(r.state.enemyTurnCount,i+1);assert.equal(r.state.enemyPhase?.completedTurns,i+1);if(i%7===4){assert.equal(r.state.rngState,s.rngState);assert.equal(r.resolution!.events.filter(e=>e.type==='enemy-wait').length,1);}s=r.state;}assert.deepEqual(counts,[1,1,1,1,0,2,2,1,1,1,1,0,2,2]);});
test('Mother Core threshold is inclusive, unrounded, and resets the phase at its next own turn',()=>{const b=config('mother-core',5);for(const [max,current,critical] of [[150,31,false],[150,30,true],[151,31,false],[151,30,true]] as const){const s=createBattle({...b,combatants:{...b.combatants,enemy:{...b.combatants.enemy,maxHp:max,initialHp:current}}});assert.deepEqual(stepTypes(getEnemyIntent(s)),critical?['fixed-damage','drop']:['drop','drop']);const r=enemy(s);assert.equal(r.state.enemyPhase?.phase,critical?'critical':'normal');assert.equal(r.state.enemyPhase?.completedTurns,critical?1:6);assert.equal(r.resolution!.events.some(e=>e.type==='enemy-phase'),critical);if(critical){assert.deepEqual(stepTypes(getEnemyIntent(r.state)),['drop']);const next=enemy(activeEnemy(r.state));assert.equal(next.state.enemyPhase?.completedTurns,2);assert.deepEqual(stepTypes(getEnemyIntent(next.state)),['fixed-damage','drop']);}}});
test('crossing low HP through a player action does not start an enemy sub-action inside that action',()=>{const b=config('mother-core',5);const s=createBattle({...b,firstActor:'player',initialBoxes:[box(7,0,'player'),box(7,1,'player')],combatants:{...b.combatants,enemy:{...b.combatants.enemy,initialHp:31}}});const r=applyAction(s,{type:'drop',candidateId:'ceiling:2:0'});assert.equal(r.state.hp.enemy.current,27);assert.equal(r.state.enemyTurnCount,5);assert.equal(r.state.enemyPhase?.phase,'normal');assert.equal(r.resolution!.events.some(e=>e.type==='enemy-phase'),false);const turn=enemy(r.state);assert.equal(turn.resolution!.events[0]!.type,'enemy-phase');assert.equal(turn.state.hp.player.current,25);});
test('low HP phase does not re-enter or reset every turn',()=>{let s=createBattle({...config('mother-core',6),combatants:{...config().combatants,enemy:{...config().combatants.enemy,initialHp:30}}});const a=enemy(s);s={...a.state,actor:'enemy',hp:{...a.state.hp,enemy:{...a.state.hp.enemy,current:100}}};assert.deepEqual(stepTypes(getEnemyIntent(s)),['drop']);const b=enemy(s);assert.equal(b.resolution!.events.some(e=>e.type==='enemy-phase'),false);assert.equal(b.state.enemyPhase?.phase,'critical');});
test('two-drop attack guard is shared across the entire enemy turn',()=>{const b=config('mother-core',5);const s=createBattle({...b,board:{width:1,height:4,gravity:'down',terrain:[],invalidCells:[]},initialBoxes:[box(2),box(3)],initialBuild:{...createPlayerBuild('blue'),slots:[createSkill('first-guard'),null]},combatants:{...b.combatants,player:{maxHp:50,initialHp:50,attacks:{3:4,4:7,5:11}}}});const r=enemy(s);assert.deepEqual(r.resolution!.events.filter(e=>e.type==='attack').map(e=>e.damage),[3,8]);assert.equal(r.state.hp.player.current,39);assert.equal(r.state.gauge,11);assert.equal(r.resolution!.activeOrigins?.length,2);assert.equal(r.state.enemyTurnCount,6);assert.equal(r.state.turn,2);});
test('second insertion uses updated board and its own attack geometry',()=>{const b=config('mother-core',5);const s=createBattle({...b,board:{width:1,height:4,gravity:'down',terrain:[],invalidCells:[]},initialBoxes:[box(3)]});const r=enemy(s);const drops=r.resolution!.events.filter(e=>e.type==='drop');assert.deepEqual(drops.map(e=>e.landing.row),[2,1]);assert.equal(r.resolution!.events.filter(e=>e.type==='attack').length,1);assert.equal(r.state.hp.player.current,25);assert.equal(r.resolution!.activeOrigins?.[0]!.links[0]!.count,2);assert.equal(r.resolution!.activeOrigins?.[1]!.links[0]!.count,3);});
test('first insertion KO completes its axis attacks but prevents the second insertion and RNG draw',()=>{const b=config('mother-core',5);const s=createBattle({...b,board:{width:3,height:3,gravity:'down',terrain:[],invalidCells:[]},initialBoxes:[box(0,0),box(0,2),box(1,0,'neutral'),box(1,1),box(1,2,'neutral'),box(2,0,'neutral'),box(2,1),box(2,2,'neutral')],combatants:{...b.combatants,player:{...b.combatants.player,initialHp:1}}});const r=enemy(s);assert.equal(r.resolution!.events.filter(e=>e.type==='drop').length,1);assert.equal(r.resolution!.events.filter(e=>e.type==='attack').length,2);assert.equal(r.resolution!.activeOrigins?.length,1);assert.equal(r.state.result?.winner,'enemy');assert.equal(r.state.gauge,1);assert.equal(r.state.boxes.length,9);assert.equal(r.resolution!.events.some(e=>e.type==='instant-kill'),false);});
test('board filling after first nonlethal drop makes second planned drop a lethal fallback',()=>{const b=config('mother-core',5);const s=createBattle({...b,board:{width:1,height:1,gravity:'down',terrain:[],invalidCells:[]}});const r=enemy(s);assert.equal(r.resolution!.events.filter(e=>e.type==='drop').length,1);assert.equal(r.resolution!.events.filter(e=>e.type==='instant-kill').length,1);assert.equal(r.state.result?.reason,'enemy-blocked');assert.equal(r.state.enemyTurnCount,6);assert.equal(r.state.gauge,30);});
test('wait remains a wait on a full board with no lethal fallback',()=>{const b=config('mother-core',4);const s=createBattle({...b,board:{width:1,height:1,gravity:'down',terrain:[],invalidCells:[]},initialBoxes:[box(0)]});const r=enemy(s);assert.deepEqual(r.resolution!.events.map(e=>e.type),['enemy-wait']);assert.deepEqual(r.state.hp,s.hp);assert.equal(r.state.rngState,s.rngState);assert.equal(r.state.result,null);assert.equal(r.state.actor,'player');});
test('second loop fixed attack adds only its configured bonus',()=>{const b=config('speed-core',4);const r=enemy(createBattle({...b,enemyFixedDamageBonus:1}));assert.equal(r.state.hp.player.current,26);assert.equal(r.state.gauge,4);const m=config('mother-core');const s=createBattle({...m,enemyFixedDamageBonus:1,combatants:{...m.combatants,enemy:{...m.combatants.enemy,initialHp:30}}});assert.equal(enemy(s).state.hp.player.current,24);});
test('stage50 victory offers one category and continues to stage51 with carry and scaled stats',async()=>{const setup=prepareTrialSetup({ending:'legacy-endless',character:'blue',firstEnemy:'marujiro',seed:1,mode:'manual',stage:50,fixture:'reward',route:'boss-loop'});const {c}=controller(setup.config,50);await c.drop('ceiling:2:0');assert.equal(c.runSnapshot!.stage,50);assert.equal(c.runSnapshot!.status,'reward');assert.equal(c.runSnapshot!.defeatedCount,1);const id=c.runSnapshot!.offer!.id;await c.chooseCategory(id,'heal');assert.equal(c.runSnapshot!.stage,51);assert.equal(c.snapshot.config.enemyId,'marujiro');assert.equal(c.snapshot.hp.enemy.max,180);assert.deepEqual(c.snapshot.config.combatants.enemy.attacks,{3:4,4:6,5:8});assert.equal(c.snapshot.enemyTurnCount,0);assert.equal(c.snapshot.enemyPhase,undefined);assert.equal(c.snapshot.hp.player.current,28);assert.equal(await c.chooseCategory(id,'heal'),false);await c.restart();assert.equal(c.runSnapshot!.stage,50);assert.equal(c.snapshot.hp.enemy.max,640);assert.equal(c.snapshot.enemyTurnCount,0);});
test('transition24→25 uses boss stats once; pulse test seeds reset at the next encounter',async()=>{const setup=prepareTrialSetup({ending:'legacy-endless',character:'blue',firstEnemy:'marujiro',seed:7,mode:'manual',stage:24,fixture:'reward',route:'boss-loop'});const {c}=controller({...setup.config,initialEnemyTurnCount:4},24);await c.drop('ceiling:2:0');await c.chooseCategory(c.runSnapshot!.offer!.id,'heal');assert.equal(c.runSnapshot!.stage,25);assert.equal(c.snapshot.config.enemyId,'speed-core');assert.equal(c.snapshot.hp.enemy.max,290);assert.equal(c.snapshot.enemyTurnCount,0);assert.deepEqual(c.snapshot.config.combatants.enemy.attacks,{3:6,4:7,5:9});});
test('boss test setup uses committed stage/phase seeds and rejects invalid stage',()=>{const f=(fixture:'speed-pulse'|'mother-wait'|'mother-double'|'mother-critical',stage:number)=>prepareTrialSetup({ending:'legacy-endless',character:'blue',firstEnemy:'marujiro',seed:7,mode:'manual',stage,fixture,route:'boss-loop'});assert.deepEqual(stepTypes(getEnemyIntent(createBattle(f('speed-pulse',75).config))),['fixed-damage','drop']);assert.equal(f('speed-pulse',75).config.combatants.enemy.maxHp,870);assert.deepEqual(stepTypes(getEnemyIntent(createBattle(f('mother-wait',100).config))),['wait']);assert.deepEqual(stepTypes(getEnemyIntent(createBattle(f('mother-double',50).config))),['drop','drop']);assert.deepEqual(stepTypes(getEnemyIntent(createBattle(f('mother-critical',50).config))),['fixed-damage','drop']);assert.throws(()=>f('speed-pulse',0));});
test('mid-route setup keeps its selected rotation origin through later encounters',async()=>{
 for(const [stage,firstEnemy,nextEnemy,nextHp] of [[23,'marujiro','nigirin',260],[25,'hikikizan','nigirin',280],[75,'marujiro','hikikizan',840]] as const){
  const setup=prepareTrialSetup({ending:'legacy-endless',character:'blue',firstEnemy,seed:7,mode:'manual',stage,fixture:'reward',route:'boss-loop'});
  const c=new BattleController(setup.config,{render(){},async animate(){}},setup.options);
  await c.drop('ceiling:2:0');await c.chooseCategory(c.runSnapshot!.offer!.id,'heal');
  assert.equal(c.runSnapshot!.stage,stage+1);assert.equal(c.snapshot.config.enemyId,nextEnemy);assert.equal(c.snapshot.hp.enemy.max,nextHp);
 }
});
test('restart during multi-drop presentation never replays committed boss work in the new run',async()=>{
 let release!:()=>void;const b=config('mother-core',5);const c=new BattleController(b,{render(){},animate:()=>new Promise<void>(r=>{release=r;})});const pending=c.start();
 assert.equal(c.snapshot.boxes.length,2);assert.equal(await c.drop('ceiling:0:0'),false);
 await c.restart(createTrialConfig());release();await pending;assert.equal(c.snapshot.boxes.length,0);assert.equal(c.snapshot.enemyTurnCount,0);assert.equal(c.snapshot.enemyPhase,undefined);assert.equal(c.snapshot.actor,'player');
});
