import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
import {createProfile,drawGacha,characterDrawPool,ProfileStore,META,validateProfile} from '../src/next/meta/profile.ts';import {rosterIds} from '../src/next/meta/roster.ts';import {characterGachaOdds,percentLabel} from '../src/next/meta/gachaOdds.ts';
import {sampleUniformIndex} from '../src/next/core/random.ts';import {normalSkillIds,skillCatalog} from '../src/next/core/skillCatalog.ts';import {LEGACY_BOARDS} from '../src/next/meta/kits.ts';import {roster} from '../src/next/meta/roster.ts';
const all=rosterIds.filter(id=>id!=='blue'&&id!=='red');
// Baseline algorithm differs only in the source pool, not categories, prices or transaction behavior.
const source=readFileSync(new URL('../src/next/meta/profile.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('profile.ts',source,ts.ScriptTarget.Latest,true),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='drawGacha')!;
const js=ts.transpileModule(node.getText(ast).replace('export function drawGacha','function baselineDraw').replace('characterDrawPool(n)',"rosterIds.filter(id=>id!=='blue'&&id!=='red')")+'\nreturn baselineDraw;', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
const baseline=new Function('META','sampleUniformIndex','rosterIds','normalSkillIds','skillCatalog','LEGACY_BOARDS','roster',js)(META,sampleUniformIndex,rosterIds,normalSkillIds,skillCatalog,LEGACY_BOARDS,roster) as typeof drawGacha;
test('all64 collection states select only missing characters until complete, with accurate next-draw odds',()=>{
 for(let mask=0;mask<64;mask++){const p=createProfile(1972);p.coins=100;p.ownedCharacters.push(...all.filter((_,i)=>mask&(1<<i)));const before=JSON.stringify(p),pool=characterDrawPool(p),missing=all.filter(id=>!p.ownedCharacters.includes(id)),odds=characterGachaOdds(p);assert.deepEqual(pool,missing.length?missing:all);assert.deepEqual(odds.candidates,pool);assert.equal(odds.missingCount,missing.length);assert.equal(odds.eachOverallPercent*pool.length,20);const n=drawGacha(p);assert.equal(n.lastDraw!.kind,'character');assert(pool.includes(n.lastDraw!.item as typeof all[number]));assert.equal(n.lastDraw!.duplicate,missing.length===0);assert.equal(n.energy-p.energy,missing.length?0:3);assert.equal(n.coins,0);assert.equal(n.drawCount,1);assert(n.pendingDraw);assert.equal(JSON.stringify(p),before);validateProfile(n);if(!missing.length)assert.deepEqual(n,baseline(p));}
});
test('non-character outcomes are identical to the previous rule, with no RNG reset or coin/skill/energy changes',()=>{let checked=0;for(let i=0;i<2000;i++){const p=createProfile((Math.imul(i,2654435761)+123)>>>0);p.coins=1000;p.ownedCharacters.push('mint','amber');const old=baseline(p),next=drawGacha(p);if(old.lastDraw!.kind!=='character'){assert.deepEqual(next,old);checked++;}}assert(checked>1500);});
test('old committed pending duplicates and results survive load/acknowledgement without retroactive conversion',()=>{const p=createProfile(1972);p.coins=100;p.ownedCharacters.push('mint');const old=baseline(p);assert.equal(old.lastDraw!.kind,'character');assert(old.lastDraw!.duplicate);const raw=JSON.stringify(old);assert.throws(()=>drawGacha(old));assert.equal(JSON.stringify(old),raw);const data=new Map<string,string>();const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};const store=new ProfileStore(storage,()=>true);store.read();store.write(old);const reload=new ProfileStore(storage,()=>true);reload.read();assert.deepEqual(reload.current.lastDraw,old.lastDraw);assert.equal(reload.current.energy,old.energy);reload.update(x=>{x.pendingDraw=false;return x;});assert.deepEqual(reload.current.lastDraw,old.lastDraw);});
test('before-write and persisted-then-throw retries keep exactly one debit/result/new character',()=>{for(const fault of ['before','after'] as const){const data=new Map<string,string>();let fail=false;const storage={getItem:(k:string)=>data.get(k)??null,setItem(k:string,v:string){if(fail&&fault==='before')throw Error('quota');data.set(k,v);if(fail&&fault==='after'){fail=false;throw Error('uncertain');}}};const store=new ProfileStore(storage,()=>true);store.read();store.update(p=>{p.coins=500;p.rng=1972;p.ownedCharacters.push('mint');return p;});const old=store.current,expected=drawGacha(old);fail=true;assert.throws(()=>store.update(drawGacha));fail=false;store.guard();if(!store.current.pendingDraw)store.update(drawGacha);const current=store.current;assert.equal(current.coins,expected.coins);assert.equal(current.rng,expected.rng);assert.equal(current.drawCount,1);assert.deepEqual(current.lastDraw,expected.lastDraw);assert.deepEqual(current.ownedCharacters,expected.ownedCharacters);assert.throws(()=>store.update(drawGacha));assert.equal(store.current.drawCount,1);}});
test('insufficient coins and pending results leave every existing receipt/build/XP value unchanged',()=>{const p=createProfile(2);const raw=JSON.stringify(p);assert.throws(()=>drawGacha(p));assert.equal(JSON.stringify(p),raw);p.coins=100;p.pendingDraw=true;const pending=JSON.stringify(p);assert.throws(()=>drawGacha(p));assert.equal(JSON.stringify(p),pending);});
test('probability copy rounds honestly and never claims fixed individual rates or a draw-count guarantee',()=>{assert.equal(percentLabel(20/6),'約3.33%');assert.equal(percentLabel(20/3),'約6.67%');assert.equal(percentLabel(10),'10%');const p=createProfile();assert.match(characterGachaOdds(p).summary,/未所持の6人/);p.ownedCharacters.push(...all.slice(0,5));assert.match(characterGachaOdds(p).summary,/各20%/);p.ownedCharacters.push(all[5]!);assert.match(characterGachaOdds(p).summary,/全6人/);const home=readFileSync(new URL('../src/next/meta/home.ts',import.meta.url),'utf8');assert.match(home,/<summary>排出確率/);assert.match(home,/percentLabel\(odds.eachOverallPercent\)/);assert.match(home,/class="gacha-odds"/);assert.doesNotMatch(home,/確率は全抽選で一定/);});

test('a new character result preserves accumulated XP, builds, pools, trophies and settlement records',()=>{
 const p=createProfile(1972);p.coins=500;p.energy=9;p.characters.blue.xp=1234;p.characters.red.xp=70;p.receipts['previous-run']={runId:'previous-run',character:'blue',xp:20,coins:10,defeated:2,clear:false,trophies:[],at:12};p.launches['active-run']={character:'red',snapshot:'{"version":1}'};p.trophies['clear50:first']=1;validateProfile(p);
 const n=drawGacha(p);assert.equal(n.lastDraw!.kind,'character');assert.deepEqual(n.characters,p.characters);assert.deepEqual(n.receipts,p.receipts);assert.deepEqual(n.launches,p.launches);assert.deepEqual(n.trophies,p.trophies);assert.deepEqual(n.ownedSkills,p.ownedSkills);assert.equal(n.selected,p.selected);assert.equal(n.energy,9);assert.equal(n.coins,400);assert.notEqual(n.rng,p.rng);
});
