import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {playerGuideData,playerGuideHtml} from '../scripts/docs/build-player-guide.mts';import {rosterIds} from '../src/next/meta/roster.ts';import {META,treeNodes} from '../src/next/meta/profile.ts';import {boardSkillName,currentBoardInformation,currentFormInformation} from '../src/next/ui/kitInformation.ts';
const html=readFileSync(new URL('../public/docs/game1_content_catalog_next.html',import.meta.url),'utf8'),json=JSON.parse(readFileSync(new URL('../public/docs/game1_content_catalog_next.json',import.meta.url),'utf8'));
test('published guide output is an exact deterministic render of current source definitions',()=>{assert.equal(html,playerGuideHtml());assert.deepEqual(json.playerGuide,playerGuideData());assert.equal(json.revision,'1.12');assert.equal(json.skills.length,35);assert.equal(json.fixedPassives.length,1);});
test('guide includes all8 roles, every legal free/unlocked board, exact cost text and frozen-run warning',()=>{const d=playerGuideData();assert.deepEqual(d.characters.map(c=>c.id),rosterIds);for(const c of d.characters){assert(html.includes(`id="character-${c.id}"`));assert.equal(c.form,currentFormInformation(c.id));for(const b of c.boards){assert.equal(b.name,boardSkillName(b.id));assert.equal(b.description,currentBoardInformation(b.id));assert(html.includes(b.name));}}assert(html.includes('以前のランの構成や育成条件を途中で置き換えません'));});
test('growth thresholds, economy, pool and safety limits remain explicit',()=>{const d=playerGuideData();assert.deepEqual(d.levels.map(x=>x.xp),[0,40,100,180,280,400,540,700,880,1080,1300,1540]);assert.equal(d.levels.at(-1)!.points,24);assert.equal(Object.values(treeNodes).reduce((n,x)=>n+x.max*x.cost,0),29);assert.equal(META.gachaCost,100);for(const text of ['450コイン・750EXP','0体なら0','20÷N%','全所持時の候補は青35、ほか34','アカウント同期・クラウド保存はありません','成長バックアップに戦闘途中のセーブは含まれません','全キャラが上限なら、現時点ではエナジーの使用先はありません','毒・トゲ・自己コスト・投入不能は防ぎません'])assert(html.includes(text),text);assert.doesNotMatch(html,/\/workspace|\/tmp\/|worker|普遍的.*勝率|iOS.*検証済み/);});
test('guide anchor navigation and character summaries are self-contained without scripts or external requests',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);for(const a of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(a[1]));assert.equal((html.match(/class="character"/g)??[]).length,8);assert.doesNotMatch(html,/<script|https?:\/\//);assert(html.includes('@media(max-width:560px)'));});

test('verification note separates functional checks, fixed-policy studies and unresolved limits',()=>{const html=playerGuideHtml();assert.match(html,/育成Lv8の同条件で全8キャラ・計288ラン/);assert.match(html,/32ランずつ2回/);assert.match(html,/人のクリア率/);assert.match(html,/ローズとバイオレット/);assert.match(html,/横リンク＋12/);assert.match(html,/採用していません/);assert.match(html,/iOS実機/);assert.match(html,/音の実聴品質/);assert.doesNotMatch(html,/workspace|subagent|tool_call|worker/i);});

// 日本語: ガチャ案内は新しい連数と即時保存に一致させる。English: Guide follows batch pricing and commit-before-reveal.
test('gacha guide explains ten draws and no acknowledgement gate',()=>{const section=playerGuideHtml().split('<section id="gacha">')[1]!.split('</section>')[0]!;assert.match(section,/10連/);assert.match(section,/900コイン/);assert.match(section,/確認ボタンはなく/);assert.match(section,/初入手キャラクター/);assert.doesNotMatch(section,/前回の結果を確認してから/);});
