import test from 'node:test';import assert from 'node:assert/strict';
import {ProfileStore,createProfile,validateProfile} from '../src/next/meta/profile.ts';
import {tutorialCatalog,tutorialCompleted,tutorialListHtml,completeBasicTutorial,awardCompletedTutorials} from '../src/next/meta/tutorialCatalog.ts';
import {advanceTreeTutorial} from '../src/next/meta/treeTutorial.ts';
const memory=()=>{const data=new Map<string,string>();return {data,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};};
test('catalog renders the requested titles, rewards and stamps only for completed tutorials',()=>{const p=createProfile();assert.equal(tutorialCatalog.length,2);assert(!tutorialListHtml(p).includes('tutorial-stamp'));completeBasicTutorial(p);assert(tutorialCompleted(p,'basic'));assert.equal(tutorialListHtml(p).match(/tutorial-stamp/g)?.length,1);for(const item of tutorialCatalog)assert(tutorialListHtml(p).includes(item.title));});
test('basic and tree completion each award exactly100, persist final acknowledgement and ignore duplicates',()=>{
 const m=memory(),s=new ProfileStore(m,()=>true);s.read();const start=s.current.coins;
 s.update(p=>{completeBasicTutorial(p);completeBasicTutorial(p);return p;});assert.equal(s.current.coins,start+100);
 for(let step=0;step<21;step++)s.update(p=>{assert(advanceTreeTutorial(p,step));assert(!advanceTreeTutorial(p,step));awardCompletedTutorials(p);return p;});assert.equal(s.current.coins,start+100);assert(!tutorialCompleted(s.current,'tree'));
 const resumed=new ProfileStore(m,()=>true);resumed.read();resumed.update(p=>{assert(advanceTreeTutorial(p,21));awardCompletedTutorials(p);return p;});
 const reloaded=new ProfileStore(m,()=>true);reloaded.read();for(let i=0;i<5;i++)reloaded.update(p=>{advanceTreeTutorial(p,21);awardCompletedTutorials(p);completeBasicTutorial(p);return p;});assert.equal(reloaded.current.coins,start+200);validateProfile(reloaded.current);
});
test('legacy basic recipients keep their award; existing tree completions get the new reward once',()=>{const p=createProfile();completeBasicTutorial(p);p.treeTutorial={step:21,completed:true};const before=p.coins;awardCompletedTutorials(p);assert.equal(p.coins,before+100);awardCompletedTutorials(p);assert.equal(p.coins,before+100);});
test('interruption and failed save never commit a completion or reward',()=>{const m=memory();const s=new ProfileStore(m,()=>true);s.read();s.update(p=>{advanceTreeTutorial(p,0);return p;});const raw=m.getItem(s.key);const fail=new ProfileStore({getItem:m.getItem,setItem(){throw Error('quota');}},()=>true);fail.read();assert.throws(()=>fail.update(p=>{p.treeTutorial={step:21,completed:true};awardCompletedTutorials(p);return p;}));assert.equal(m.getItem(s.key),raw);assert(!s.current.receipts['tutorial-tree-v1']);});
test('write-then-throw and immediate reload cannot duplicate rewards',()=>{const m=memory(),s=new ProfileStore(m,()=>true);s.read();const start=s.current.coins;const fail=new ProfileStore({getItem:m.getItem,setItem(k,v){m.setItem(k,v);throw Error('late');}},()=>true);fail.read();assert.throws(()=>fail.update(p=>{completeBasicTutorial(p);return p;}));const reloaded=new ProfileStore(m,()=>true);reloaded.read();reloaded.update(p=>{completeBasicTutorial(p);return p;});assert.equal(reloaded.current.coins,start+100);});
test('old backup import preserves both received tutorial receipts',async()=>{const m=memory(),s=new ProfileStore(m,()=>true);s.read();const old=s.current;s.update(p=>{completeBasicTutorial(p);p.treeTutorial={step:21,completed:true};awardCompletedTutorials(p);return p;});await s.importBackup(old);const coins=s.current.coins;s.update(p=>{completeBasicTutorial(p);awardCompletedTutorials(p);return p;});assert.equal(s.current.coins,coins);assert(s.current.receipts['tutorial-tree-v1']);assert(tutorialCompleted(s.current,'tree'));});
